### ISSUE TITLE
2.1-amd64 seems to include an old ESH version

### ISSUE THREAD

**Issue by Spybyte** [openhab/openhab-docker#101]
Hey,

I use the docker offered by docker hub and also build my own container. The ESH version include is0.9.0.b5 (which will be outdated in some days). 
See also https://github.com/eclipse/smarthome/issues/4130#issuecomment-325339707

There seemed to be several problems in this version, which have been fixed in later versions. Is there any chance to include the latest version in the docker image? Or some work around?

Cheers
Björn

**Comment by kaikreuzer** [comment]
2.1-amd64 includes the openHAB 2.1 release, which used ESH 0.9.0.b5, so all is fine.

If you want anything newer, you will have to use 2.2.0-snapshot instead.
