### ISSUE TITLE
Update docker docs on user id handling

### ISSUE THREAD

**Issue by dominikkv** [openhab/openhab-docker#105]
Hi,

for me as a beginner it was not clear that the id for the host user "openhab" has to match the id of the docker container user "openhab".

So please in the docs make clear that either
- the created host user & group "openhab:openhab" both has to have the id 9001
```
groupadd -g 9001 openhab
useradd -u 9001 -g openhab -r -s /sbin/nologin openhab
usermod -a -G openhab openhab
usermod -a -G openhab mydefaultuser
```
- or the user id has to be passed to the container through env AND the container has to run as the host openhab user
`--user <openhabuserid> -e "USER_ID=<openhabuserid>"`

(is that correct?)

Thanks
Dominik

**Comment by dominikkv** [comment]
I made a pull request: https://github.com/openhab/openhab-docker/pull/106

**Comment by cniweb** [comment]
Thanks
