### ISSUE TITLE
How to automatically install extensions after docker container startup

### ISSUE THREAD

**Issue by CodingSpiderFox** [openhab/openhab-docker#110]
As a user, I want to bring up a new openhab instance quickly in case the machine dies where I run openhab on.

I want to be able to mount a config file in my docker-compose config in which I can tell openhab which extensions to install.

**Comment by FlorianSW** [comment]
Do you mean addons for openHAB? If so, I generally add the addons to install into the conf/services/addons.cfg file. Addons listed there should be installed, once openHAB starts. There's nothing you need to do with docker to achieve this, as long as the config directory is a volume and saved somewhere outside the container (which is a good idea in general, too) :)

**Comment by CodingSpiderFox** [comment]
Thanks

**Comment by FlorianSW** [comment]
So, can this issue be closed?

**Comment by CodingSpiderFox** [comment]
I think so
