### ISSUE TITLE
Typo in Dockerfile

### ISSUE THREAD

**Issue by patrickse** [openhab/openhab-docker#120]
The label of the Dockerfile contains

```
    org.label-schema.vendor="penHAB Foundation e.V." \
```

I guess the *o* in *openHAB Foundation is missing.

https://github.com/openhab/openhab-docker/blob/958ef6b6b025bfc61eaaab10d0be3f9cf5065412/2.1.0/armhf/alpine/Dockerfile#L34

**Comment by cniweb** [comment]
Fixed with #119
