### ISSUE TITLE
Please include vim package for the vi editor into docker images

### ISSUE THREAD

**Issue by doc1138** [openhab/openhab-docker#121]
As a UNIX geek I would kindly appreciate to have the classic vi editor available in all of the docker images. Hence please consider including the vim package for a future release.

Thank you very much!

**Comment by larsskj** [comment]
Would that be a good idea? Docker images are supposed to be slim and only contain the absolute minimum needed to run an application.

If you really want vi - I use it a lot as well - you could easily build your own Docker image based on this one - but including vi: In that way you get vi, and the rest of us get slimmer containers.

**Comment by doc1138** [comment]
I raised this request in agreement with Christian (cniweb). I would assume that at least one editor should be included in an docker image of that kind. I must admit that I did not realize that all vim packages together (vim,vim-common, vim-runtime) are about 30MB. Hence I understand your comment ... But I still think that there should be one editor in the image and I do not mean "sed" ;-)

**Comment by cniweb** [comment]
I think @larsskj is right. The image should contain only what openhab needs to run.

@doc1138, you can login into container with:

`docker exec -it <container> bash`

and run:

```
apt-get update
apt-get install vim
```

That should not be enough.

**Comment by cniweb** [comment]
After careful consideration, we came to the decision not to integrate an editor into the docker image.
No editor is required to run openhab.

**Comment by doc1138** [comment]
As I found that the whole vim stuff takes around 30MB I agree that the space "wasted" is not worth the value. I agree to keep it off the container. In the meantime I also got more understanding what files really need to be edited and how to mount them from the outside and therefore edit them with an editor also outside the container. Thanks for consideration!
