### ISSUE TITLE
Suggestion / question: more tags

### ISSUE THREAD

**Issue by martinvw** [openhab/openhab-docker#125]
This week we had some troubles and because of that I really needed to switch back to a previous docker version but there is no way to fetch an old snapshot, so I was curious whether it would be possible to tag the dailies with there build number*

The actual build number can be requested from Jenkins at: https://openhab.ci.cloudbees.com/job/openHAB-Distribution/lastSuccessfulBuild/buildNumber

It would be great if I could switch back in times trouble to for example:

`openhab/openhab:2.1.0-snapshot-amd64-debian-1078`

Is that possible and desirable @cniweb ?

* maybe a cleanup after two week would be appropriate

**Comment by cniweb** [comment]
Hi Martin,

I pass the question on @kaikreuzer because I think that this problem have other providers of install packages too.
Because I think, from the artefact repository you can only download the last snapshot version.
I thought under debian, for example, you only get the latest package if you update the package.

But in general it would certainly be possible.

Chris

**Comment by martinvw** [comment]
Hi @cniweb,

Is that actually a problem, because imho as soon as the docker image is build there are no new downloads required or am I mistaken? 

At least during the build I see it fetching it or are the docker images also stored in the artefact repository?

JFrog stores the last 5 builds, see https://openhab.jfrog.io/openhab/libs-snapshot-local/org/openhab/distro/openhab/2.2.0-SNAPSHOT/

Regards,

Martin

**Comment by cniweb** [comment]
Hi @martinvw ,

I think I need the URL for the last builded zip.
I need the zip file from last build.
History is here:
https://openhab.jfrog.io/openhab/webapp/#/builds/openHAB-Distribution
But how is the ZIP file URL from the artefact?

Regards,
Chris

**Comment by cniweb** [comment]
Hi @martinvw 

Wait, I think wrong. The build number of the Jenkins build is sufficient. So you could still fit the day of the Docker images.
Each successful build of the snapshot distribution could create its own docker image tag.

Regards,
Chris

**Comment by kaikreuzer** [comment]
> JFrog stores the last 5 builds

If this is enough of history, then you could probably revert to them. But you should avoid that people expect they can move to any previous build version easily. After all, this is a snapshot build, so it is intended to always only have the latest available.
Once we have more regular release builds, the situation will change.

**Comment by martinvw** [comment]
@kaikreuzer So you do not like the idea? Or your don't want to put new things for it in place?

**Comment by kaikreuzer** [comment]
I do not know what changes this means for docker and I would leave that to you experts.

**Comment by martinvw** [comment]
I fear that we have to refactor the travis job if we want to integrate this, we can make a job with [multiple stages](https://docs.travis-ci.com/user/build-stages/) and make one of them [conditional](https://docs.travis-ci.com/user/conditional-builds-stages-jobs/). In that extra stage for snapshots we can then add an extra tag next to the existing one, something like:

```
BUILDNR="`wget -qO- https://openhab.ci.cloudbees.com/job/openHAB-Distribution/lastSuccessfulBuild/buildNumber`"
docker tag $DOCKER_REPO:$VERSION-$TARGET-$DIST $DOCKER_REPO:$VERSION-$TARGET-$DIST-$BUILDNR
```

@cniweb wdyt?

**Comment by kaikreuzer** [comment]
Please note that we are working on a completely new Jenkins build pipeline (https://openhab.ci.cloudbees.com/view/Sandbox%20Release%20Pipeline/job/sandbox-openhab2-release/), so maybe it would make sense to directly see how that would fit in there.

**Comment by cniweb** [comment]
I think that with the build number in the image tag would be already possible.

I had already planned a conversion from Travis to Jenkins anyway.

How many snapshots should be kept?
An automated deletion of image tags in the Docker hub should be possible.

**Comment by martinvw** [comment]
14 (days) would be great in this case we went from 1078 to 1096 in a week and _some users still report errors_. Maybe 25 or 30 tags?

**Comment by wborn** [comment]
You already easily create your own local container image tag ofcourse before updating as a backup. So you wouldn't even have to remember what build number you were using:

`docker tag openhab/openhab:2.2.0-snapshot-amd64-debian openhab/openhab:my-latest-working-version`

**Comment by martinvw** [comment]
This one is more about buildnumbers, so the subject is a little different it would help you go back to an older build of the snapshot

**Comment by martinvw** [comment]
I would suppose #192 should be closed
