### ISSUE TITLE
Warn Alpine image users about possible incompatiblities because of OpenJDK dependency

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-docker#130]
The Alpine Docker images are [using OpenJDK](https://github.com/openhab/openhab-docker/blob/master/2.1.0/amd64/alpine/Dockerfile#L57) but there are no warnings about possible incompatibilities.

Possible OpenJDK incompatiblities are mentioned in:
* [Prerequisites documentation](http://docs.openhab.org/installation/index.html#prerequisites)
* Community Discussions: [Example 1](https://community.openhab.org/t/docker-image-openjdk-oracle/33631), [Example 2](https://community.openhab.org/t/running-openhab-2-on-openjdk/21443)

**Comment by cniweb** [comment]
What exactly do you mean, which Java should we use in Alpine Linux?

**Comment by wborn** [comment]
My issue is about that users can choose between the debian and alpine image options but they are not warned enough about known incompatibilities (see links in first comment) with running openHAB with OpenJDK on alpine:

----

## README.md

**Distributions:**

* ``debian`` for debian jessie
* ``alpine`` for alpine 3.6

If you are unsure about what your needs are, you probably want to use
 ``openhab/openhab:2.2.0-amd64-debian``.

----

I think a line about mentioning that alpine uses OpenJDK and a link to the known issues of using openHAB with OpenJDK in [Prerequisites](https://docs.openhab.org/installation/#prerequisites) would be enough. 

It does seem to be possible to run Zulu on Alpine, see this image: https://hub.docker.com/r/azul/zulu-openjdk-alpine/tags/

Most likely the images will become about as big as the debian images due their glibc dependencies. So one of the biggest advantages of using Alpine would be lost. Though there would probably be less compatibility issues.

**Comment by cniweb** [comment]
OK, how should the hint then look in the readme?

**Comment by wborn** [comment]
How about?

**Distributions:**

* ``debian`` for debian jessie
* ``alpine`` for alpine 3.6

The alpine images are substantially smaller than the debian images but may be less compatible because OpenJDK is used (see [Prerequisites](https://docs.openhab.org/installation/#prerequisites) for known disadvantages).

If you are unsure about what your needs are, you probably want to use
 ``openhab/openhab:2.2.0-amd64-debian``.

**Comment by cniweb** [comment]
That sounds good, I'll include it
