### ISSUE TITLE
Problem with new version 2.2.0-amd64-alpine

### ISSUE THREAD

**Issue by gabylan12** [openhab/openhab-docker#139]
I want to upgrade version of the container but i have the next problem

`
openhab_develop | Hit '<tab>' for a list of available commands
openhab_develop | and '[cmd] --help' for help on a specific command.
openhab_develop | Hit '<ctrl-d>' or type 'system:shutdown' or 'logout' to shutdown openHAB.
openhab_develop | 
openhab_develop | openhab> Error executing command: java.lang.NullPointerException
`

Where can i see more information?

**Comment by wborn** [comment]
Perhaps you're starting the container without a tty? See also: https://github.com/openhab/openhab-docker/issues/133
