### ISSUE TITLE
Correct shutdown of Karaf

### ISSUE THREAD

**Issue by sja** [openhab/openhab-docker#14]
I noticed that if I run the container as "debug", the karaf client is not started in entrypoint.sh with exec. On normal start, it is. As a result, karaf is sometimes PID 1, sometimes the bash which executes entrypoint.sh is PID 1.

That becomes important if you try to stop the container. You will have a zombie process. (`docker stop` never ends)

I prefixed the start with dumb-init from yelp to have an as simple as possible handler for docker containers. That worked, but the karaf container is not shut down correctly - it's just killed. The karaf console says, it just shuts down on ctrl-d (which is an EOF, not a real process signal).

Any ideas how to finalize that, that karaf shuts down correctly? Then I can finish my PR for this.

**Comment by cyberkov** [comment]
Hello!
Sorry for my late response. Unfortuantely I cannot be of help in that case, as I was struggling as well with karaf and it's shell... which is the reason for the exec/eval part in the entrypoint.
I would like to keep the external components used in the docker container as low as possible (dockerize, dumb-init, supervisor) until some final solution to the PID1 problem has emerged from the docker community. It might make sense to replace all eval calls by directly invoking:
```exec "/openhab/runtime/karaf/bin/karaf" "${@}"```.
What do you think about that?

Cheers Hannes

**Comment by legacycode** [comment]
@sja could you please try version 2.1.0-snapshot?

```
PID TTY      STAT   TIME COMMAND
    1 ?        Ss+    0:00 /bin/bash ./runtime/bin/karaf
  106 ?        Sl+    0:16 /usr/lib/java-8/bin/java -Dopenhab.home=/openhab -Dopenhab.conf=/openhab/conf -Dopenhab.runtime=/openhab/runtime -Dopenha
```

You can also start the container in debug mode by running:

  ```
PID TTY      STAT   TIME COMMAND
    1 ?        Ss+    0:00 /bin/bash ./runtime/bin/karaf debug
  106 ?        Sl+    0:13 /usr/lib/java-8/bin/java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -Dopenhab.home=/openhab -Dope
```

This shoud fix yout problem.

**Comment by sja** [comment]
Will try that, thanks.

**Comment by sja** [comment]
👍  Seems to work. (Tested with Ubuntu Xenial, docker 1.12)
