### ISSUE TITLE
Exit container with helpful error message when pseudo tty is missing

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-docker#140]
It's easy to forget starting the openhab 2.2.0 container with a pseudo tty. Instead of instructing people to read the documentation the container should also be able to detect this and exit with a helpful message.

For example the `test.sh` script like the one below can detect the tty configuration:

```
#!/bin/sh

tty > /dev/null 2>&1

if [ $? -eq 1 ]; then
    echo "Please start the openHAB container with a pseudo tty using the -t option or 'tty: true' with docker compose"
    exit 1
fi;

echo "tty properly set!"
exit 0
```

After a quick test it seems to work well when creating the containers with and without the tty:

Alpine:
* docker run --rm -v $PWD/test.sh:/test.sh alpine:3.7 /test.sh
* docker run --rm -t -v $PWD/test.sh:/test.sh alpine:3.7 /test.sh

Debian Jessie:
* docker run --rm -v "$PWD/test.sh:/test.sh" multiarch/debian-debootstrap:amd64-jessie /test.sh
* docker run --rm -t -v "$PWD/test.sh:/test.sh" multiarch/debian-debootstrap:amd64-jessie /test.sh

**Comment by wborn** [comment]
We also need to add the use of the -t option to the [openHAB Docker documentation](http://docs.openhab.org/installation/docker.html). It seems to be missing there.

**Comment by cniweb** [comment]
https://github.com/openhab/openhab-docs/pull/600#pullrequestreview-85326826
