### ISSUE TITLE
can't update: curl not found

### ISSUE THREAD

**Issue by dmartinpro** [openhab/openhab-docker#143]
When trying to use the update script (runtime/bin/update), I'm facing an error due to the lack of curl package in the image.
Could you please add it to the Dockerfile?

**Comment by cniweb** [comment]
In debian or alpine?

**Comment by dmartinpro** [comment]
both, afaik. I'm currently using Debian 'cause Alpine has another severe problem (see issue #144 )

**Comment by wborn** [comment]
I think there are more issues with running the update script in the container than the missing curl command. So it needs to be thoroughly tested. E.g. it also does not properly detect that openhab is still running using this check:

```
  ## Check to see if processes are running before updating
  if [ ! -z "$(ps aux  | grep "openhab2.*java" | grep -v grep)" ]; then
    echo "openHAB is running! Please stop the process before updating." >&2
    exit 1
  fi
```

**Comment by dmartinpro** [comment]
Agreed, but I used it successfully with the Debian image, specifically modified with curl dependency. Adding curl is a first, and necessary, step IMHO.

**Comment by cniweb** [comment]
OK, I Adding curl as a first, and necessary, step. 
What else is needed?

**Comment by pedymaster** [comment]
Hi,
Iam just wondering, why did you not put curl into debian image too? I could really use it and cannot quite understand why only alpine was updated with curl since the reporter said it is missing in both debian and alpine.
Thank you
