### ISSUE TITLE
Test version.properties and if the build is different perform an upgrade of userdata

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-docker#148]
See:

https://community.openhab.org/t/fresh-installation-does-not-start-up/32536/13
https://community.openhab.org/t/announcing-openhab-2-2/37438/12

It is discussed elsewhere.

General approach, check if the build-no is different in userdata verses usersdata.dist. If they are different then:

- create a backup of userdata
- copy over the needed userdata.dist/etc files to userdata/etc
- delete the contents of userdata/cache and userdata/tmp

Look for a PR in a few moments.

**Comment by cniweb** [comment]
Thanks, @rkoshak 
You have to run the update script!

**Comment by rkoshak** [comment]
Can't run the update script without curl installed and apparently curl is not included in the apt-cache for the Debian image. Not sure what else to do from here. I'm not that advanced with Docker image creation.

@BClark09, you can ignore my request for review. I'm dead in the water anyway until I can figure out how to get curl into the image. Feel free to close this PR out. It will be quite some time until I can figure that out.

For the record, as implemented it appears to work great.

**Comment by cniweb** [comment]
I think, we can close this issue?

**Comment by rkoshak** [comment]
Yes. Thanks!
