### ISSUE TITLE
Add installation instructions to official OH2 documentation

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-docker#15]
It would be great if someone (@cniweb?) could provide a PR for the page http://docs.openhab.org/installation/docker.html, so that Docker is covered in the official documentation as well.

Please see https://github.com/openhab/openhab-docs/blob/gh-pages/README.md#contributing-to-the-documentation on how to do this.

**Comment by cyberkov** [comment]
I'm closing this issue since the documentation is up :)
