### ISSUE TITLE
[Feature] Include arping with the necessary suid permissions for Network Binding

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-docker#158]
I'm not certain this is feasible or not. It will be a week or so before I have a chance to try anything myself but if someone has already tried and failed please post here and I'll close the issue.

It sure would be nice to have arping available to the Network binding. I don't know how feasible it is to have setuid permissions on arping in the container but based on my current understanding it should work. 

Theoretically, all that needs to be done is to install arping to the standard location, then `chmod u+s /usr/sbin/arping`. I know we can't do dhcplisten without running as root, but support for arping without running as root would be a boon to OH Docker users.

**Comment by cniweb** [comment]
Actually, in a Docker container, ONLY should be what the application needs to run.

**Comment by cniweb** [comment]
For debian, I think we need only add arping package:
https://github.com/TeDomum/docker-arping/blob/master/Dockerfile#L4

**Comment by JHCD** [comment]
As long as "Allow System Pings" is enabled by default in the Network-Binding, the Docker image should have the functionality. To install the appropriate package manually after each update of the Docker image is annoying.

**Comment by cniweb** [comment]
Should we install the appropriate package now?

**Comment by rkoshak** [comment]
I think installing ping and arping in the same PR makes sense. I had forgotten that ping isn't in the container rendering the default behavior of the Network Binding invalid. I've always set the allow system pings parameter to false so it doesn't come up for me much.

**Comment by cniweb** [comment]
@rkoshak Well, do you create a PR for the Ping and Arping installation?

**Comment by rkoshak** [comment]
If someone wants to jump in and make the changes before I get a chance that is fine. It will be this weekend or sometime next week before I'll get a chance to create and test out a PR myself. But if no one else steps in I plan to submit a PR.

**Comment by cniweb** [comment]
@rkoshak Thank you in advance for your engagement!

**Comment by martinvw** [comment]
Hello @rkoshak, it seems this has fallen silent :-)

I was just looking at my docker container and its error about the arping :-)

**Comment by rkoshak** [comment]
I haven't had a chance to do much beyond replying on the forum this year. As soon as I can get a couple of hours next to each other without a five-year-old hanging off one leg and a cranky 70-year-old dad who is prone to getting computer viruses hanging off the other I hope to submit a PR. 

The actual change is almost trivial, just add iputils-ping and arping to the apt-get install command in the Dockerfile. The problem is the time to test.

If anyone does have the time to make the change and test it out I'd be grateful. Otherwise, it is still on my to-do list.

**Comment by martinvw** [comment]
> As soon as I can get a couple of hours next to each other without a five-year-old hanging off one leg and a cranky 70-year-old dad who is prone to getting computer viruses hanging off the other I hope to submit a PR.

I do not have the 70-year-old-dad, however I do have a 1, 4 and 6 year old hanging off one leg 😆 

Just finally got some time to to properly integrate some devices and set up my motion sensor on the attic, I still want do many other openHAB and ESH things. Now we have in Europe also the GDPR coming for which I need to some work for an organisation for which I do some volunteering work. So I totally understand the feeling.

Thanks for your great work on the forum!

**Comment by RockClimber81** [comment]
Hi,

due to lack of a 70 year old dad and children I thought I might give it a try.

Everything works like a charm in the 2.2.0 debian armhf image.
I added just the following lines in the basepackages area:

**DEBIAN**
```
# Install basepackages
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    ca-certificates \
    dirmngr \
    fontconfig \
    gnupg \
    libpcap-dev \
    locales \
    locales-all \
    netbase \
    unzip \
    wget \
    zip \
--- Edit Start
    arping && \
    chmod u+s /usr/sbin/arping && \
    ln -s -f /usr/sbin/arping /usr/bin/arping && \
--- Edit End
    ln -s -f /bin/true /usr/bin/chfn
```

I wanted to do the same for testing in the corresponding alpine Dockerfile. But it seems like something went wrong. 

**ALPINE**
```
# Install basepackages
RUN apk upgrade --no-cache && \
    apk add --no-cache --virtual build-dependencies dpkg gnupg && \
    apk add --no-cache \
    bash \
    ca-certificates \
    fontconfig \
    libpcap-dev \
    shadow \
    su-exec \
    ttf-dejavu \
    openjdk8 \
    unzip \
    wget \
    zip \
    arping
```

Docker tells me the image is up and running since an hour. But if I try to tail the log file the log file appears but it seems like nothing is written to it.

Maybe you guys have an idea whats wrong.

My compose file:
```
version: '2.1'

services:
  openhab:
    image: "openhab/openhab:2.2.0-armhf-alpine-arp"
    restart: always
    container_name: oh-apline-arp
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    tty: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/docker/volumes/openhab-alpine/addons:/openhab/addons"
      - "/docker/volumes/openhab-alpine/conf:/openhab/conf"
      - "/docker/volumes/openhab-alpine/userdata:/openhab/userdata"
    command: "./start_debug.sh"
```

I already tried to take a look into the log files in the container. But nothing there is  nothing under /var/log.
Any ideas?

**Comment by RockClimber81** [comment]
Hi Richard,

you're really everwhere... Just studied an entry in the forum from you. :D

I have no experience with alpine neither. Now after a short break I was having the thought the alpine image might be broken. I will try tomorrow or the day after with a fresh clean build of the alpine image. What bothers me it that it is almost as if the operation system within the container starts but for some reason openhab does not fire up. I am little bit lost and out of idea as there seems to be no logging within the container.

Next things on my list are:
1) Add "normal" ping to debian image (I just checked, it is not installed)
2) Pull a fresh alpine image from docker hub and check if that starts -> if not I will open a separate issue
3) Pull a fresh copy of this repo, build a clean image and check if that fires up

Cheers!

**Comment by martinvw** [comment]
> But nothing there is nothing under /var/log.

I would expects logs `/openhab/userdata/log`

And if you run it in debug mode I would suppose that you get more feedback if you do not run it detached.

> I'm also a little bit surprised by the image name `openhab/openhab:2.2.0-armhf-alpine-arp`, are you sure its correct. If I build images locally they can never include `openhab/`. Or did I just do something wrong those times ;-)

**Comment by martinvw** [comment]
I just checked I can run the existing alpine image in this case, but I have problems actually exposing the port. So I can connect to the container and request the pages, but I cannot reach it from the outside.

```bash
laptop-106359:openhab-alpine-test mvanwinger$ wget http://localhost:8080/
--2018-05-17 07:48:12--  http://localhost:8080/
Resolving localhost... ::1, 127.0.0.1, fe80::1
Connecting to localhost|::1|:8080... failed: Connection refused.
Connecting to localhost|127.0.0.1|:8080... failed: Connection refused.
Connecting to localhost|fe80::1|:8080... failed: Connection refused.
laptop-106359:openhab-alpine-test mvanwinger$ docker exec -it openhab-alpine-test_openhab_1 /bin/sh
/openhab # wget http://localhost:8080
--2018-05-17 05:49:06--  http://localhost:8080/
Resolving localhost... ::1, 127.0.0.1
Connecting to localhost|::1|:8080... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://localhost:8080/start/index [following]
--2018-05-17 05:49:06--  http://localhost:8080/start/index
Reusing existing connection to [localhost]:8080.
HTTP request sent, awaiting response... 200 OK
Length: 3897 (3.8K) [text/html]
Saving to: 'index.html.1'

index.html.1        100%[===================>]   3.81K  --.-KB/s    in 0s      

2018-05-17 05:49:06 (30.4 MB/s) - 'index.html.1' saved [3897/3897]
/openhab # netstat -nl |grep 8080
tcp        0      0 :::8080                 :::*                    LISTEN      
```

@cniweb do you know users of the alpine image, is there something wrong with our configurations?

I minimized the config to:

```
version: '2.1'
  
services:
  openhab:
    image: "openhab/openhab:2.2.0-amd64-alpine"
    network_mode: host
    tty: true
    command: "./start_debug.sh"
```

**Comment by martinvw** [comment]
It might of course be caused by running docker-compose with `network_mode = host` on a Mac

**Comment by RockClimber81** [comment]
> I would expects logs /openhab/userdata/log

Yes, the openhab log itself would be located there. But, due to it is not populated I tried do check the system logs in the container. Under Linux the logs are usually stored under /var/log. 

> I'm also a little bit surprised by the image name openhab/openhab:2.2.0-armhf-alpine-arp, are you sure its correct. 

I tagged the image like this. If there is something I learned in 10 years as Product Architect than always to tag and versioning everthing. Elsewise I get confused.

To do so just run:
```
docker build -t openhab/openhab:2.2.0-armhf-alpine-arp .
```

There seems definitely something off with the armhf alpine image. If I don't use the detach parameter -d I get the usual output but it ends with:
```
oh-apline-arp | '/openhab/userdata.dist/.' -> '/openhab/userdata/.'
oh-apline-arp | + cmp /openhab/userdata/etc/version.properties /openhab/userdata.dist/etc/version.properties
oh-apline-arp | + [ ! -z ]
oh-apline-arp | + ls -A /openhab/conf
oh-apline-arp | + [ -z html
oh-apline-arp | icons
oh-apline-arp | items
oh-apline-arp | persistence
oh-apline-arp | rules
oh-apline-arp | scripts
oh-apline-arp | services
oh-apline-arp | sitemaps
oh-apline-arp | sounds
oh-apline-arp | things
oh-apline-arp | transform ]
oh-apline-arp | + chown -R openhab:openhab /openhab
oh-apline-arp | + exec ./start_debug.sh
oh-apline-arp | Launching the openHAB runtime...
oh-apline-arp | Listening for transport dt_socket at address: 5005
oh-apline-arp exited with code 0
```
If I call docker ps afterwards I see an uptime or a few seconds.

This happens for both the docker image I pull from the registry and for the image I build myself.

**Comment by rkoshak** [comment]
>Yes, the openhab log itself would be located there. But, due to it is not populated I tried do check the system logs in the container. Under Linux the logs are usually stored under /var/log.

I'm pretty sure the OH installed in the Image is a manual install which means the logs would go in /openhab/userdata/logs inside the container. That is where they are for me at least.

> If I call docker ps afterwards I see an uptime of a few seconds.

Do you see any anything written to syslog on the host? If you use -–log-driver syslog it basically shunts all the sout and serr to the host's syslog. So everything that gets printed by entrypoint.sh and the startup of OH before openhab.log gets created still gets captured. You can grep on the containerID to narrow down to just stuff commning from that container.

In other contexts when I see this sort of behavior it is usually caused by a bad logger config or a bad java version. I'm not sure either of those would apply here.

**Comment by RockClimber81** [comment]
Hi Richard,

nice to read from you. If you like to you can give it try. I forked the repository (in my account) and pushed my changes back to github. It is already 10 PM here in Germany, I am exhausted and I will call it a day.

**Comment by RockClimber81** [comment]
> Do you see any anything written to syslog on the host? If you use -–log-driver syslog it basically shunts all the sout and serr to the host's syslog.

@rkoshak: I created a separate issue on this topic.

Back to the ping topic:
Does anybody have an idea why the network bind in 2.3.0 snapshot is very slow in discovering devices and discovers only a fraction of devices?

Does anybody volunteer to test the changes I made to the dockerfile on non-arm systems?
