### ISSUE TITLE
Synology DS412+, CPU INTEL Atom D2700, standard_init_linux.go:189: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by danhae** [openhab/openhab-docker#159]
Hi Guys,
It's my first github-post, so i hope the place is right.

I'm trying to start a docker openhab2 on my Synology DS412+.

On my 'Synology Docker App' is no way to choose the i386-architecture.

Is it possible to add the i386-architecture to https://hub.docker.com/r/openhab/openhab/ ?

I'm a docker-beginner, and i'm not able to make it via CLI and a dockerfile.

I would be very happy if somebody can help me.

Best regards from Düsseldorf, Germany.
Daniel

**Comment by cniweb** [comment]
Hi Daniel,

you can use the `amd64` architecture!
I use also the `amd64` image on a Synology DS3615xs

Best regards from Coburg, Germany :wink:
Chris

**Comment by danhae** [comment]
Hi @cniweb,
thank you for your answer.
I tested it again and it work. Sorry for wasting your time.
I'm very confused at the moment :-).
Best regrads
Daniel
