### ISSUE TITLE
Custom Logging?

### ISSUE THREAD

**Issue by polarathene** [openhab/openhab-docker#16]
I'd like to log a binding to it's own file. I've read that this is handled by `logback.xml`. 

Wiki Documentation [says ](https://github.com/openhab/openhab/wiki/Configuring-the-openHAB-runtime#logging) to use: `/opt/openhab/configurations/logback.xml`, but with this container would that now be `/openhab/conf/logback.xml`?

For KNX wiki docs [say](https://github.com/openhab/openhab/wiki/KNX-Binding#knx-logging) to add a KNX logger with this addition:
`<logger name="tuwien.auto.calimero" level="DEBUG" />`
I don't think this is the case for openHAB2 though? According to this [comment](https://github.com/openhab/openhab2-addons/issues/631#issuecomment-172300659), I should be using:
`<logger name="org.openhab.binding.knx" level="DEBUG" />`

The newer docs talk about [logging differently with karaf](http://docs.openhab.org/administration/logging.html). Instead there is the console method which is easy enough, but for persistent logging I am told to edit a config file `org.ops4j.pax.logging.cfg`, with the container I presume the files location is meant to be `/openhab/runtime/karaf/etc` now? The file does not exist, should I create it? I'm new to Java/Karaf and haven't found the documentation too clear.

If I can still use the logback.xml method presumably this will work for file contents?:
```
<appender name="KNX" class="ch.qos.logback.core.rolling.RollingFileAppender">
	<file>logs/knx.log</file>
	<rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
		<!-- weekly rollover and archiving -->
		<fileNamePattern>logs/script-%d{yyyy-ww}.log.zip</fileNamePattern>
		<!-- keep 30 days' worth of history -->
		<maxHistory>30</maxHistory>
	</rollingPolicy>
	<encoder>
		<pattern>%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{30}[:%line]- %msg%n%ex{5}</pattern>
	</encoder>
</appender>

<logger name="org.openhab.binding.knx" level="DEBUG" >
	<appender-ref ref="KNX" />
</logger>
```

Could someone clarify which methods I can use out of the above and what the recommended method is for OH2 when used in a Docker container?

**Comment by cyberkov** [comment]
Hello @polarathene!
Thank you for opening this issue. 

> The file does not exist, should I create it?
Yes I think so. You can overwrite files by using a file in the volume definition. If this does not work, please consider posting a thread in the forum as there will be more helpful eyes on the problem :)

Cheers
Hannes

**Comment by polarathene** [comment]
@cyberkov Is there a place for docs for the Docker image or should these differences be added to the openhab github wiki or newer docs(not sure how to contribute to those).

**Comment by cyberkov** [comment]
Hello!
I'm glad you ask. Actually I was hoping you would like to add it to the documentation :)
I think you can do a normal PR against [openhab/openhab-docs](https://github.com/openhab/openhab-docs)'s logging section, as the docker container is supposed to be "just another method of installation" :)

Thanks in advance!

Cheers
Hannes

**Comment by polarathene** [comment]
Cheers, will contribute to documentation after I finish getting a working setup :)

**Comment by marbon87** [comment]
@polarathene did you figure out how to customize the logback configuration?
I tried it with the following config in my docker-compose.yml and a proper volume mount, but the config is not used
```
environment:
    - "EXTRA_JAVA_OPTS=-Dlogback.configurationFile=/openhab/conf/logback.xml"
```
