### ISSUE TITLE
Serial port not ready on container start?

### ISSUE THREAD

**Issue by joe540** [openhab/openhab-docker#160]
Hi,

every time I restart my host (that auto restart the container on boot), the Z-Wave Binding fail to initialize my controller because "port doesn't exist". The port is passed using `--device /dev/ttyAMC0 `. When I'm logged to the UI, the port is there and if I edit a configuration (like the Heal time) to be able to save it, it does works correctly. If I restart the container after the first boot, it works also

Is anybody having the same problem?

Any ideas?

Thanks
Jonathan

**Comment by joe540** [comment]
I ended up adding a 30 seconds delay in the beginning of /entrypoint.sh, which fix my issue.

Thanks

**Comment by cniweb** [comment]
Would this workaround be interesting for everyone?

**Comment by joe540** [comment]
I really don't know if I'm alone having that issue, but in my case, when the host was first started and the container started automatically by the docker daemon (with --restart=always) I was having that problem.

I didn't test if a lower delay would be enough, I personally think that a 30 second delay on start doesn't harm, but if people are not using the Z-Wave binding (or other bindings that needs a serial port?) that might be annoying. I didn't check if there was a way to wait for the serial port to be ready (instead of an arbitrary 30 sec) either.

**Comment by cniweb** [comment]
OK, then we leave this issue open for a few more days. If nobody answers, we close it.

**Comment by maisun** [comment]
> I ended up adding a 30 seconds delay in the beginning of /entrypoint.sh, which fix my issue.
> 
> Thanks

Hi sorry to dig into an old issue. I'm suffering from similar problem, restart of OH container sometimes throws error "IOException Could not find a gateway on given path '/dev/ttyUSB0', 0 ports available." I'd like to give a try to add the delay, can you share how did you add the delay in startup? Thanks!

**Comment by SingingFrog7** [comment]
Hello,

 Sorry for the delay. It's been a long time and I don't use OpenHab anymore. I simply modified the entrypoint.sh file of the docker image and added a delay at the beginning (probably something like `sleep 30`).

I don't have the docker image on hand, so I can't help more right now, but let me know if you can't understand how to do it.

That will just fix the issue when the container is started too quickly after the host boot though

**Comment by SingingFrog7** [comment]
Have a look at **Executing shell scripts before openHAB is started** in the readme, or modify the entrypoint.sh and build the image (see **Building the image** in the readme)
