### ISSUE TITLE
libusb requires write access to USB device nodes.

### ISSUE THREAD

**Issue by DutchmanNL** [openhab/openhab-docker#176]
Hi folks,

I currently try running openhab on a Synology docker setup with RFXcom device to switch my 433MHZ devices.
However i am unable to use the RFXcom device, the docker log states:

```
libusb couldn't open USB device /dev/bus/usb/001/005: Permission denied.
libusb requires write access to USB device nodes.
```

The device is located at /dev/ttyUSB0, following actions have been performed:

- run container with high privileges = same result
- run chmod 777 on /dev/ttyUSB0 = same result

ls - l on /dev/ttyUSB0 shows :

`crwxrwxrwx 1 root root 188, 0 Jun 11 16:58 /dev/ttyUSB0`

For my z-wave stick, which is located at /dev/ttyACM0 i have no issue. Stick is recognised and working.
Running an equal setup with access rights like mentioned above and domoticz runs smoothly, RFXcom is recognised and usable only with openhab i have this error.

container version used :
![screen shot 2018-06-11 at 19 28 31](https://user-images.githubusercontent.com/7318445/41247233-b057fbf6-6dad-11e8-8261-f33cbfa9b722.png)

**Comment by wborn** [comment]
> Running an equal setup with access rights like mentioned above and domoticz runs smoothly

Maybe you need to load the additional USB kernel modules on your NAS? Domoticz has a package which takes care of that. I had a look at that in this [community topic](https://community.openhab.org/t/get-serial-devices-working-on-synology-ds216-ii-diskstation/36072).

**Comment by DutchmanNL** [comment]
related kernal packages are already loaded, without i wouldn't be able to see on which ttyxxxx a device is attached. 

access rights & startup file as mentioned in that post are also set equally.
Strange fact is that my USB-Zwave device works perfectly and is recognised at ttyACM0, only the RFXcom has issue. (works correctly directly connected to a windows machine running OH)

**Comment by wborn** [comment]
* What Docker command/options do you use to start the container?
* Which Synology NAS are you using?

**Comment by DutchmanNL** [comment]
For 1 : no additional comments, just used the gui to load and setup th4 HO docker container

For 2 : DS1618+

**Comment by wborn** [comment]
Did you also apply the instructions from the RFXCom Binding Linux Note so JD2XX that is used by the binding can take over? See: https://www.openhab.org/addons/bindings/rfxcom/#note-linux

Do you create the container from the command line or the Synology UI? 
IIRC the `--device` parameter (normally used for USB devices) can not be configured in the Synology UI. 
For Docker command parameters see: https://github.com/openhab/openhab-docker#parameters

Maybe @martinvw has some more ideas on how to get RFXCom working with Docker.

**Comment by martinvw** [comment]
It could be an architectural problem because my docker on amd64 works flawlessly with an rfxcom. I ‘ll try to post some config later today

**Comment by DutchmanNL** [comment]
I did not execute the commands related to RFXCom Binding Linux Note so JD2XX.
Could try that later today but didn't thought this would help as the error clearly states an access right issue.

The container itself is created by GUI and I use currently high privileged option. The Z-wave USB device works without issue on the same setup

**Comment by DutchmanNL** [comment]
small update :

Running openhab with the related synology package did have the same issue, after starting openhab as root user the RFXcom is connected and working as expected.

not sure if we will see the same behaviour within the docker environment, i have no clue how to stop openhab here and start it again as root user instead of user openhab

**Comment by DutchmanNL** [comment]
issue solved by adding the following lines in "" :

```
insmod /lib/modules/usbserial.ko
insmod /lib/modules/ftdi_sio.ko
sudo chmod 777 /lib/modules/usbserial.ko
sudo chmod 777 /lib/modules/ftdi_sio.ko
sudo chmod 777 /dev/ttyUSB0
```

the insmod were not enough, also the 3 sudo lines are needed to get the RFXcom device working within the docker container.

Only con : usb devices are only accessible when running the container in high privileged mode which is not my most wanted choice :/

**Comment by wborn** [comment]
Great to see you made some progress @DutchmanNL! :smiley:

I don't use RFXCom myself so I don't know what should work when dropping privileges. If I read https://github.com/openhab/openhab2-addons/issues/2316 correctly JD2XX is only necessary for automatically discovering devices.

You could also try starting the container from a terminal and add only the required capabilities so you don't need the priviliged mode, see: https://stackoverflow.com/a/36441605
Starting it from a terminal gives you more configuration options while it will still show up in the Synology UI.

**Comment by hal01** [comment]
> issue solved by adding the following lines in my startup.sh file :
> 
> ```
> insmod /lib/modules/usbserial.ko
> insmod /lib/modules/ftdi_sio.ko
> sudo chmod 777 /lib/modules/usbserial.ko
> sudo chmod 777 /lib/modules/ftdi_sio.ko
> sudo chmod 777 /dev/ttyUSB0
> ```
> 
> the insmod were not enough, also the 3 sudo lines are needed to get the RFXcom device working within the docker container.
> 
> Only con : usb devices are only accessible when running the container in high privileged mode which is not my most wanted choice :/

@DutchmanNL, I'm having the same issue than you.
I'm a beginner... 
How do you edit the start.sh script for your docker container to add the lines... I don't know where to start and I would appreciate some guidance.
Thanks a lot in advance

**Comment by wborn** [comment]
Let's close this issue since having to configure these kernel modules on the host is not an openHAB Docker container issue.
