### ISSUE TITLE
Web Pool Thread Size too low?

### ISSUE THREAD

**Issue by polarathene** [openhab/openhab-docker#18]
I have [had trouble with multiple clients](https://github.com/kaikreuzer/openhab-core/issues/51) while exploring the UIs and have concern that when openHAB is used by a multitude of users such as a large family via iOS/Android/Browser/etc clients, this problem may occur. When it does, all requests have a delay of about 15-20 seconds(perhaps can take longer with more clients), even cURL request is blocked.

I was recently pointed to [this issue](https://github.com/openhab/openhab-distro/issues/192) which seems it might be the reason why. Could the default be increased with this image, else how should I go about it?

It had a [related PR](https://github.com/openhab/openhab-distro/pull/193/files), as that is merged is the [Dockerfile just pulling in an older release](https://github.com/openhab/openhab-docker/blob/master/Dockerfile#L7)(`openhab-online-2.0.0-SNAPSHOT.zip`) and will get the fix with a newer snapshot?

**Comment by cniweb** [comment]
The new URL is:
https://bintray.com/openhab/mvn/download_file?file_path=org%2Fopenhab%2Fdistro%2Fopenhab-online%2F2.0.0.b3%2Fopenhab-online-2.0.0.b3.zip
???

**Comment by cyberkov** [comment]
Hello @polarathene!
The docker container ingests the most recent daily build from the cloudbees instance. Therefore I think the current build should already have the necessary changes in it.

@cniweb sorry, i git distracted from those brandnew debian packages :) Looks like some work coming up for us changing from zip to deb ;)

Cheers
Hannes

**Comment by polarathene** [comment]
@cyberkov I have a Dockerfile on top of the one in this repo to add a few changes. I guess the layer might be cached instead of getting the latest update? Still new to Docker so will hunt down the command to do a fresh rebuild, would be good to have in docs for others new to Docker :)

Are there newer deb packages than zip files? What is the benefit to switch to deb? I might try later on to create a Docker image based on Alpine Linux, which hopefully can use the zip unless that is Debian specific.
