### ISSUE TITLE
Adding additional addons to the image

### ISSUE THREAD

**Issue by boerreth** [openhab/openhab-docker#189]
What do I need to change if I want to also have a few more addons included in the image, like mqtt, influxdb and take away f.example hue?
Is that easy to do?

**Comment by cniweb** [comment]
Do you mean openhab addons?
In OH 2.x you can install it over the paper ui!

**Comment by boerreth** [comment]
Yes, i know that. But I am generating 7 containers in a script and I want to have most of it installed in a script. With node-red i can specify package in the docker file

**Comment by hakan42** [comment]
I do this by creating my own image based on the current openhab-docker image, and putting an adapted services/addons.cfg in it. Maybe this could help you?

**Comment by cniweb** [comment]
@boerreth help this?

**Comment by wborn** [comment]
I'll close this since there hasn't been any response for more than a year.
