### ISSUE TITLE
[Fatal Error] :1:3: The markup in the document preceding the root element must be well-formed.

### ISSUE THREAD

**Issue by polarathene** [openhab/openhab-docker#23]
I wanted to try the latest commit with additional dialout/uucp GUIDs instead of my dockerfile that made the changes for myself. I've completely cleared all my docker containers and images to avoid any cache issues(based on [this](http://stackoverflow.com/a/29357318) including the force remove in comments), then ran `docker run -it --name openhab --net=host openhab/openhab:amd64-online server` provided under [Usage on the readme](https://github.com/openhab/openhab-docker#usage).

I get the openHAB greeting graphic and 3 lines of tips. Few moments later `openhab>` prompt appears with the following error:

`[Fatal Error] :1:3: The markup in the document preceding the root element must be well-formed.`

Any idea what is causing that and how to fix it?

EDIT: I had the error prior to doing the full cache clean and Jetty server was starting up but failing to load the UI page at localhost:8080. The error is still being thrown after the full cleanup mentioned but I am able to access the UI now.  Leaving open as the error should probably be addressed?

**Comment by kaikreuzer** [comment]
See https://community.openhab.org/t/fatal-error-on-start-from-console/12417
