### ISSUE TITLE
Release pipeline question (Docker image vs Repo)

### ISSUE THREAD

**Issue by victoryNap** [openhab/openhab-docker#234]
This repo hasnt been updated in around 2 months, but the docker image has been updated today. Is there any release pipeline or tracking where the recent updates are posted?

**Comment by wborn** [comment]
The Docker images are build by [Travis CI](https://travis-ci.org/openhab/openhab-docker/builds) which gets triggered by this [Jenkins job](https://ci.openhab.org/job/openHAB2-Docker/). That build gets triggered by it's upstream [Distribution build](https://ci.openhab.org/job/openHAB-Distribution/) which is triggered by it's own upstream projects.

**Comment by cniweb** [comment]
@victoryNap right, that's exactly how it works.

**Comment by wborn** [comment]
Let's close this issue since the question has been answered and there are no further comments.
