### ISSUE TITLE
Add version 1.8.3 as another image, with new label

### ISSUE THREAD

**Issue by TimWeyand** [openhab/openhab-docker#24]
I thought finally "an official openhab docker file" and was disappointed:
- that it did not work (even in demo mode) :-(
- i could not find documentations for the docker especially for userdata
- after looking at the Dockerfile! i realized, that its not even openHAB but openHAB 2

If you don't want to separate openHAB 1 and openHAB 2 dockers, at least write it in the documentation! Or give the Option which ones to use. Many Users will take a while to migrate to openHAB 2, the product is great and you do not have to change a running system continuously.

Keep up the great work, but don't forget that there are users out there - who think differently.

**Comment by kaikreuzer** [comment]
> that it did not work (even in demo mode) :-(

Did you enter an issue about what exactly were your problems?

> i could not find documentations for the docker especially for userdata

Please help and contribute what you feel is missing!

>  at least write it in the documentation

Makes sense. Again, creating a PR to make that clear in the documentation is the fastest way to get there!

Regarding the rename request itself: I am not too fond of that idea, since there is no openhab1 repo, so there is no need to distinguish it - and calling it openhab2 might not be a very future proof naming...

P.S.: Disclaimer: I am not a maintainer of this repo here, so @cniweb is the best to talk to :-)

**Comment by TimWeyand** [comment]
>> that it did not work (even in demo mode) :-(

> Did you enter an issue about what exactly were your problems?

I am actually not sure what was going on. I started the Docker without the Hostfolder options, which should start the demo. Since i am not in openhab 2 yet and wanted to upgrade after 2 Years stable running, i wanted to use the official Docker. By the way, Thank you for the stable Application :)

>> at least write it in the documentation

>Makes sense. Again, creating a PR to make that clear in the documentation is the fastest way to get there!

I will try to do this, at least the Version declaration should be there. Since openHAB 1 and 2 are not compatible.

>Regarding the rename request itself: I am not too fond of that idea, since there is no openhab1 repo, so there is no need to distinguish it - and calling it openhab2 might not be a very future proof naming...

I would agree with you, if openhab 2 would be declared as stable. Then it would be suitable to post an openHAB 2 in the Dockerhub as the offical openHAB Version. Since it is not, it should be named as such or at least the Beta anywhere. I would not and have not expected an beta of openHAB published and therefor pushed by openhab.org as stable version. At least this is what it looks like.

As i was saying, i have the greatest respect for you all and your work on this project. But breaking changes (we had this before) and irritating things harm a project. Just look it from a new users prospektive.

**Comment by cniweb** [comment]
Hi all

This project should openHAB 1 and 2 support separated by another branch openHAB 2. In Dockerhub could then be differentiated by labels. What do you all mean?

**Comment by TimWeyand** [comment]
Hi Chris,
that would be a great idea! It would not be confusing for new Users and old ones. 

Best,
Tim

**Comment by cniweb** [comment]
Hi all,

OK, then I create a corresponding branch and customize the files.
@cyberkov what do you think?

Chris

**Comment by JustinAiken** [comment]
So there will be a usable openhab1 docker coming here!!!? 😀

**Comment by cniweb** [comment]
Hi @JustinAiken,

thanks for your feedback!
I have already created a new branch:
https://github.com/openhab/openhab-docker/tree/openHAB2

Chris

**Comment by kaikreuzer** [comment]
@cniweb This change only makes sense if you really plan to provide an openHAB 1 version.
And in this case, I would treat openHAB1 as a branch and having the latest development (=openHAB2) on master.
On Dockerhub, you should also clearly mark openhab1 and openhab2 then.

**Comment by cniweb** [comment]
OK Kai, I agree with you. I'll create a openHAB1 branch ...

**Comment by TimWeyand** [comment]
Hi,
since i wrote this post - i have been working on my two year old docker image (based on the work of @tdeckers and a lot of others). Maybe this could be a base for an openhab 1 branch docker.

* It pulls the version (1) based on the environment at build time. 
* Adds Addons based on a text config
* Its possible to change Ports and IP based on Environment variables (since i had problems with knx, i needed this option for --net=host)
* It runs in DEMO mode, if no config is given.

https://hub.docker.com/r/tweyand/openhab/
https://github.com/TimWeyand/docker-openhab/tree/master

**Comment by cniweb** [comment]
Hi @TimWeyand 

that´s look good.
Can we use your Dockerfile for openHAB1?

Thanks,
Chris

**Comment by TimWeyand** [comment]
Hi Chris,
of course you can use my Dockerfile

Best,
Tim

**Comment by cniweb** [comment]
Hi @TimWeyand

can you contribute your Dockerfile in our new struture (subfolder 1.8.3)?
@legacycode wath do you think?

Thanks,
Chris

**Comment by legacycode** [comment]
@cniweb I dont think we should create a folder for the 1.8.3 version. Since this post was created many time is gone and version 2.0 is stable now. I think that more and more people will migrate to the new version. We should focus to the actual versions with our capacity.

**Comment by cyberkov** [comment]
Agree. Closing. 
Cheers Hannes
