### ISSUE TITLE
pgrep missing for runtime/bin/restore

### ISSUE THREAD

**Issue by esticle** [openhab/openhab-docker#246]
Hi,

Cosmetic item - the procps package should probably be installed by default for when you want to use runtime/bin/restore to restore a backup.

From the runtime/bin/restore script:

```
  ## Check to see if processes are running before restoring
  if [ ! -z "$(pgrep -f "openhab2.*java")" ]; then
    echo "openHAB is running! Please stop the process before restoring." >&2
    exit 1
  fi
```

**Comment by cniweb** [comment]
Hi @esticle,

thanks for your issue.
I think we need this packages:
for Alpine:
https://pkgs.alpinelinux.org/package/edge/main/x86/procps
for Debian:
https://packages.debian.org/buster/i386/procps/filelist

Correct?

**Comment by esticle** [comment]
For Debian it is procps as well:

```
testuser@pi07:~$ docker exec -it openhab /bin/bash
root@pi07:/openhab# dpkg -S `which pgrep`
procps: /usr/bin/pgrep
root@pi07:/openhab# cat /etc/debian_version 
10.0
```
