### ISSUE TITLE
Docker doesn't load

### ISSUE THREAD

**Issue by Steve-1234** [openhab/openhab-docker#248]
I get the following message when I pull your container:
latest: Pulling from wborn/openhab-jdk11
no matching manifest for unknown in the manifest list entries

**Comment by wborn** [comment]
Does it work if you use the official openhab/openhab docker images? 
Maybe you can also list what OS/Architecture and Docker version you use?

Older Docker versions don't have multi architecture support so you'll also need to specify your architecture using the `openhab/openhab:<version>-<architecture>-<distribution>` scheme.

E.g.:

`openhab/openhab:2.4.0-amd64-debian`

See: [Image variants](https://github.com/openhab/openhab-docker#image-variants)

**Comment by wborn** [comment]
I assume the lack of response suggests this is no longer an issue.
Feel free to reopen it if you have additional information!
The [community forum](https://community.openhab.org) is also a good place for getting questions answered . :-)
