### ISSUE TITLE
UI Failing to install/load?

### ISSUE THREAD

**Issue by 1activegeek** [openhab/openhab-docker#25]
So I was using an older image and hadn't touched it in awhile. Decided to start a fresh container and download a fresh image. I will post below the command used to start the container if it's of value. The problem I'm running into, is that it seems to start ok, but according the OpenHAB logs, it's looking like the UI is failing to load.

Docker Run command:
`docker run -d -p 8083:8080 -p 8042:8443 -p 5555:5555 -v /etc/localtime:/etc/localtime:ro -v /etc/timezone:/etc/timezone:ro -v /media/dockerdata/openhab2/conf:/openhab/conf -v /media/dockerdata/openhab2/userdata:/openhab/userdata -v /media/logging/openhab2:/openhab/userdata/logs --device=/dev/ttyACM0 --name=oh2 openhab/openhab:amd64-online`

Log Output (truncated to the first bits of line)
`2016-08-01 21:46:57.818 [INFO ] [org.eclipse.smarthome.ui.basic      ] - FrameworkEvent INFO - org.eclipse.smarthome.ui.basic
org.osgi.framework.BundleException: The bundle class path entry "patch/" could not be found for the bundle "osgi.identity; osgi.identity="org.eclipse.smarthome.ui.basic"; type="osgi.bundle"; version:Version="0.9.0.201607271614""`
`2016-08-01 21:46:57.940 [INFO ] [org.eclipse.smarthome.ui.paper      ] - FrameworkEvent INFO - org.eclipse.smarthome.ui.paper
org.osgi.framework.BundleException: The bundle class path entry "patch/" could not be found for the bundle "osgi.identity; osgi.identity="org.eclipse.smarthome.ui.paper"; type="osgi.bundle"; version:Version="0.9.0.201607271614"; singleton:="true""`
`2016-08-01 21:46:59.600 [ERROR] [org.ops4j.pax.web.pax-web-jetty     ] - FrameworkEvent ERROR - org.ops4j.pax.web.pax-web-jetty
org.osgi.framework.BundleException: Could not resolve module: org.ops4j.pax.web.pax-web-jetty [147]
  Unresolved requirement: Import-Package: org.ops4j.pax.web.jsp; version="4.2.4"; resolution:="optional"
  Unresolved requirement: Import-Package: org.apache.xbean.finder; version="[4.1.0,5.0.0)"`

Output of `docker logs`

`````` openhab>
+ set -euo pipefail
+ IFS='
    '
++ ls -A /openhab/userdata
+ '[' -z 'cache
etc
generated-bundles
kar
lock
logs
mapdb
port
tmp' ']'
++ ls -A /openhab/conf
+ '[' -z 'html
items
persistence
rules
scripts
services
sitemaps
things
transform' ']'
+ '[' server = server ']'
+ eval /openhab/start.sh
++ /openhab/start.sh
Launching the openHAB runtime...

                          __  _____    ____      
  ____  ____  ___  ____  / / / /   |  / __ )     
 / __ \/ __ \/ _ \/ __ \/ /_/ / /| | / __  | 
/ /_/ / /_/ /  __/ / / / __  / ___ |/ /_/ /      
\____/ .___/\___/_/ /_/_/ /_/_/  |_/_____/     
    /_/                        2.0.0-SNAPSHOT

Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
Hit '<ctrl-d>' or type 'system:shutdown' or 'logout' to shutdown openHAB.```
``````

**Comment by 1activegeek** [comment]
Any updates or ideas here what is happening? I'm guessing I must be missing something small here, but in just not able to figure it out and this is extremely frustrating as I'm trying to build a new system for a new home.

**Comment by legacycode** [comment]
@1activegeek: Does this problem still exists?

**Comment by 1activegeek** [comment]
I'll mark this as closed as I no longer have the version and instance of OpenHAB running. Sorry for leaving it lingering. I've since made a swatch of changes including moving from one host to another, changing the backend storage (and permissions), and altered the docker config being used. Currently I'm running by leaving the content inside the docker container volume and backing up as a workaround. Hopefully migrating to using the USER function to change user running in container.
