### ISSUE TITLE
Remove auto-generated dockerfiles from repository

### ISSUE THREAD

**Issue by hakan42** [openhab/openhab-docker#250]
During the travis build, all the Dockerfiles are regenerated.

If we would remove the pregenerated ones from the repository, it would be clearer that the real single source of truth is the "update-docker-files.sh" shell script.

So, either remove the dockerfiles or have a BIG BIG COMMENT at the start of the files that they are recreated on every build and should not be relied upon?

**Comment by wborn** [comment]
I didn't like them being the repo at first but now I do. It's a good reference to see what's in an image without first having to checkout the repo and then invoke the script. I think it also helps users who want to build slightly modified Docker images. That way they don't need to figure out how our tooling works.

> the real single source of truth is the "update-docker-files.sh" shell script.

The single source of truth is "update.sh". :wink: 

The docker files already have a [BIG BIG COMMENT](https://github.com/openhab/openhab-docker/blob/dfa27163ad0193e02530b7c8ad751eddf5e9317b/2.4.0/debian/Dockerfile-amd64#L2-L8). Maybe it should also be added to the other files. Some contributors still overlook this big comment.

**Comment by hakan42** [comment]
Ah, sorry, did not notice the BIG BIG COMMENT 😁 

I always tend to get a little bit concerned when machine-generated stuff ends up committed to the source tree, but I can also see the reasoning with "without having to invoke the script...". 

Maybe run a "git diff" after cloning on travis (and breaking the build if diffs are found?) so we can make really really sure that what we are building is precicely what is in the repo? If this is agreeable, I would come up with an appropriate PR.

**Comment by hakan42** [comment]
o.k., in that case, I have something to do during the weekend or at some late night hacking session :)

**Comment by wborn** [comment]
Another benefit of having the generated files in the repo is that it's easier to review script changes. If the generated content isn't there, it will be harder to see how script changes impact the generated content.

**Comment by cniweb** [comment]
I agree with wborn.
Can we close this Issue?

**Comment by hakan42** [comment]
Sure, I just kept it open as a reminder for me that I wanted to come up with a PR for checking during build as mentioned by wborn...
