### ISSUE TITLE
Request for socat in docker image.

### ISSUE THREAD

**Issue by hansbogert** [openhab/openhab-docker#256]
I've been running openhab on docker since early days of 2.3 and it's working fine. I'm migrating all my containers to kubernetes, and that also is working out fine for Openhab. 
Though I have one problem, my zwave dongle has a good spot in the hall closet, whereas my k8s cluster is somewhere in the attic.
Socat and ser2net would be ideal, however the current image does not have socat installed.

I understand that by incorporating socat in the docker image we are slipping into feature creep, but I can't think of a more composed way of doing this, e.g., mounting a (pseudo) tty from a sidecar container or something; but there currently is no such thing in docker/k8s.

**Comment by wborn** [comment]
You could add a startup script that installs any package you want if it hasn't been installed yet. That way you don't have to start creating your own image and we don't have to add each and every package to the image. ;-)

See: https://github.com/openhab/openhab-docker#executing-shell-scripts-before-openhab-is-started

**Comment by hansbogert** [comment]
@wborn I was actually using that already for the actual socat initialization, I guess it's fine to add the package install as well.
