### ISSUE TITLE
Milestone-Version not correct in Docker-Update-Log

### ISSUE THREAD

**Issue by CBrosius** [openhab/openhab-docker#258]
Saw this in the last 3 milestone-updates:

This time I upgraded to 2.5.0 M5

`The script will attempt to update openHAB to version 2.5.0.M2`

and

`SUCCESS: openHAB updated from 2.5.0.M4 to 2.5.0.M2`

Since 2.5.0.M2 this did not change. 
It is only cosmetic, because the upgrade indeed is running fine.

**Comment by wborn** [comment]
I think the only way it would show up like this is if you're overriding the default `OPENHAB_VERSION` environment variable value to `2.5.0.M2`. It works fine for me. :slightly_smiling_face:

**Comment by wborn** [comment]
Did you already have a look at your container environment variables configuration @CBrosius?

**Comment by CBrosius** [comment]
Yes I did, and you were right. The OPENHAB_VERSION variable is set to 2.5.0.M2

But as I did not set that by myself, it may have something to do with how I´m upgrading.
I use Portainer GUI and maybe it preserves the variable when pulling the newest image.

Thank you for your assistance, I will close the issue as it happens only in my environment.

Kindest regards,
Christian...
