### ISSUE TITLE
OpenHABrepo requires Authentication in 2.5 latest

### ISSUE THREAD

**Issue by svergata** [openhab/openhab-docker#265]
This Night release does not startup: 

Caused by: java.io.IOException: Error resolving artifact org.openhab.ui.bundles:org.openhab.ui.dashboard:jar:2.5.0: [Could not transfer artifact org.openhab.ui.bundles:org.openhab.ui.dashboard:jar:2.5.0 from/to openhab (https://api.bintray.com/maven/openhab/mvn/online-repo/2.5/): Not authorized]

**Comment by kaikreuzer** [comment]
Did you already download it last night? This issue occurred in a version that was online for 20 minute before it was replaced by a working build.

**Comment by wborn** [comment]
We pushed a new container with a fix for those URLs. 

So if you update the version in `/openhab/userdata/etc/version.properties` to 2.4.0 and recreate the container using the updated image, it will probably redo the upgrade and fix the repo URLs.

If that doesn't work try restoring the automatically generated backup.

**Comment by svergata** [comment]
Image is up-to-date, but indeed the Version hint was the right one. After the change openHAB redoes the upgrade and is now up an running again. thx 4 help

**Comment by wborn** [comment]
Great! :slightly_smiling_face:
