### ISSUE TITLE
Loop when updating from 2.4.0 to 2.5.0

### ISSUE THREAD

**Issue by janwo** [openhab/openhab-docker#267]
When updating from 2.4.0 to 2.5.0, it constantly creates backups and the log says that I am already on version 2.4 although the image is on 2.5.0.

I also did a fresh 2.4.0 install and restored my old 2.4.0 instance via the backup tool. The problem persists. :(

What's wrong?

**Comment by cebrox** [comment]
I have the same problem.

**Comment by wborn** [comment]
It's probably due to some configuration error so I suggest to ask for help in the [community](https://community.openhab.org/tags/docker).
Make sure to provide as much info as possible, like docker version/compose file/docker commands.

**Comment by janwo** [comment]
https://community.openhab.org/t/backup-loop-when-updating-docker-image-from-2-4-0-to-2-5-0/88255

@cebrox maybe comment on it to increase visibility.

**Comment by wborn** [comment]
Is this still an issue? Perhaps you can try 2.5.1?

**Comment by cebrox** [comment]
@wborn I will try in the next few days.

**Comment by cebrox** [comment]
@wborn I've tried to update from 2.4.0 to 2.5.1. Unfortunaly, i got the same error.

**Comment by cebrox** [comment]
I found a solution for this problem. I using portainer to manage my containers. There is a environment variable named OPENHAB_VERSION. When i updated the container image with portainer, this environment variable does not change automatically to the new version. I've updated this environment variable manually to 2.5.1 and the update script works.

**Comment by wborn** [comment]
Great that you've solved it! :+1: 
Looks like you're not the only one running into this Portainer specific behavior.
See: https://github.com/portainer/portainer/issues/2952
