### ISSUE TITLE
2.5.x snapshot build?

### ISSUE THREAD

**Issue by martinvw** [openhab/openhab-docker#272]
Hello, 

Is there already a 2.5.x snapshot build? 

Currently, 3.0.0 is not yet stable enough so it would be great to have a 2.5.x snapshot build.

Thanks!

cc: @wborn :-)

**Comment by wborn** [comment]
AFAIK further updates are provided by KAR files and not new distros.

See: https://github.com/orgs/openhab/teams/maintainers/discussions/2?from_comment=49#discussion-2-comment-49

**Comment by martinvw** [comment]
So that makes sense because the core will not be updated and can use the newest addons :-)

**Comment by jsetton** [comment]
Any chance to get more information related to this? I am running the latest stable 2.5.1 docker image and I can't get the latest 2.5.2-snapshot addons while they can be downloaded from the [Jenkins repository](https://ci.openhab.org/view/Integration%20Builds%20(2.5.x)/job/openHAB-Distribution/). It seems to me a 2.5.x-snapshot build should be available.

**Comment by kaikreuzer** [comment]
No, releases will only use released versions of add-ons, no snapshots.

**Comment by jsetton** [comment]
So, how do we test the 2.5.2-snapshot add-ons? My point was to have 2.5.x-snapshot docker image available. Not to use 2.5.2-snapshot add-ons with 2.5.1 release.

**Comment by martinvw** [comment]
I do believe we might be able to provide an 2.5.x-SNAPSHOT build which contains the stable core and has the proper reference to the snapshot repo such as we discussed @ FOSDEM.

@kaikreuzer would you be okay with such a solution?

**Comment by kaikreuzer** [comment]
You mean a distro build? No, I don't think it makes sense to do snapshot builds, while never intending to do a release build of it.
Why not simply edit the repo url manually, when people want to test snapshot add-ons?

**Comment by martinvw** [comment]
No I mean a docker build. Thus the stable distro with the changed repo url wrapped as a docker image.

**Comment by jsetton** [comment]
Either this or expose an environment variable that would be used by the [update script](https://github.com/openhab/openhab-docker/blob/master/openhab2-update.sh#L14) to update the add-ons locations to use the latest snapshot add-ons KAR files.

**Comment by kaikreuzer** [comment]
> No I mean a docker build.

Then don't ask me, but decide together with the @openhab/docker-maintainers :-)

**Comment by wborn** [comment]
I would prefer to keep it simple and add an image using the 2.5.2-SNAPSHOT distro (even though it may never be released).

Rationale:
* It doesn't involve additional PRs in this repo if we do decide to release it. That way users can straight away also test distro changes.
* We don't have to deal with Karaf specifics like what download URLs are used. I'm also looking forward to not having to manage the [existing download URLs](https://github.com/openhab/openhab-docker/blob/401111e558fc900c7a98ec0d7b3f0876f5693f35/update-docker-files.sh#L6-L11) in this repo when https://github.com/openhab/openhab-distro/issues/1064 is resolved.
* We can reuse most of the existing image generation code so it won't introduce further complexity in the bash scripts in this repo

**Comment by jsetton** [comment]
@wborn just a thought, if 2.5.2-SNAPSHOT docker image is added, should it be considered as the default snapshot image over 3.0.0-SNAPSHOT until the latter is usable?

**Comment by wborn** [comment]
I think it's quite subjective to determine when 3.0.0-SNAPSHOT is usable. It may never be usable for OH1 add-on users.

**Comment by jsetton** [comment]
> It may never be usable for OH1 add-on users.

That's actually a fact 😄 My comment was more oriented on some of the major functionalities, such as persistence, that still need to be ported over. Preventing most users from running 3.0.0-SNAPSHOT right now. Anyway, this was just a thought.

**Comment by kaikreuzer** [comment]
> using the 2.5.2-SNAPSHOT distro

Ah, I only noticed now that this is still built - I was actually believing that the build only produces the add-ons artifacts now as that was the plan.
But maybe it is easier to keep the distro after all, even if it means that the 2.5.2 release will be identical to 2.5.1. But it probably cause less confusion, if the download page shows the distro of the same latest version as we ship the add-ons.

**Comment by jsetton** [comment]
@wborn Thanks for merging the change. I noticed the `openhab/openhab:2.5.2-snapshot-alpine` tag is not available. It looks like this is because the `2.5.2-snapshot` tag is missing from the relevant [manifest](https://github.com/openhab/openhab-docker/blob/master/2.5.2-snapshot/alpine/manifest.yml#L2).

**Comment by wborn** [comment]
Thanks for spotting that @jsetton!
It seems to have been missing for a while :blush: and should be fixed with https://github.com/openhab/openhab-docker/pull/279.

**Comment by wborn** [comment]
Seems like the alpine images still fail to deploy because the Alpine v3.11 armhf image is missing :disappointed:

See: https://github.com/multiarch/alpine/issues/30

So maybe it's best to downgrade back to v3.10 if that still works.

**Comment by jsetton** [comment]
As far as I can see, only `2.5.2-snapshot-alpine` is missing from [Docker hub](https://hub.docker.com/r/openhab/openhab/tags?page=1&name=alpine). All the other `alpine` tags have been generated in the last update. That's very odd.

**Comment by wborn** [comment]
Those tags are a couple of weeks old and were generated when Alpine v3.10 was still used.

I've downgraded the version with https://github.com/openhab/openhab-docker/pull/280 and it will now properly fail the build when commands fail. That helps a lot because it also showed that the OH 3.0.0-SNAPSHOT build fails on Alpine because there is no openjdk11 package for armhf (https://github.com/openhab/openhab-docker/issues/281). :-/

**Comment by jsetton** [comment]
I was able to pull the `2.5.2-snapshot-alpine` docker image and is working great. Thanks!

**Comment by kaikreuzer** [comment]
> But maybe it is easier to keep the distro after all, even if it means that the 2.5.2 release will be identical to 2.5.1. But it probably cause less confusion, if the download page shows the distro of the same latest version as we ship the add-ons.

@wborn FYI, I am keeping the distro artifact in place with the current 2.5.2 build, so you can also provide docker images for the release version (as you do for the snapshots).

**Comment by wborn** [comment]
Thanks! I've updated the build for the new stable/snapshot versions with #282.
