### ISSUE TITLE
no sound from container, missing pulseaudio

### ISSUE THREAD

**Issue by vKnmnn** [openhab/openhab-docker#273]
Hi there, 
I've spent quite some time yesterday on getting the container to output sound via the host machine's pulseaudio. I'm leaving this issue here, so people can find a solution to the problem.

In the end the solution was very easy: 
add `--device /dev/snd:/dev/snd` to the container
install pulseaudio packages to the container. 
set `default-server=<ipDockerHost>` in `/etc/pulse/client.conf ` in container

This assumes that on the host `module-native-protocol-tcp auth-ip-acl=<local subnet in CIDR> auth-anonymous=1` is loaded 

The same should be possible using `module-native-protocol-unix auth-anonymous=1` on the host and an additional bind-mount of the pulseaudio socket, as well as the appropriate path in default-server directive.

since the packages required by pulseaudio, they would add 70MB to the images, which as i understand is too much.

**Comment by vKnmnn** [comment]
Marking this as solved, since the solution is included above.

**Comment by bf8392** [comment]
I tried out your guide and it installs pulseaudio. I got rid of the warning that the audio-device can't be opened, but I'm still not hearing anything...even with installing mpg123 and executing docker exec -it openhab mpg123 /openhab/conf/sounds/doorbell.mp3. It seems to decode, but I don't get any sound...can you help?

**Comment by vKnmnn** [comment]
you should try to find out if pulseaudio on the host machine registers a client connecting. 
you can do that via its log output or, if you have pavucontrol installed on your computer, from a terminal launch `ULSE_SERVER=192.168.1.2 pavucontrol` where you replace the ip with your docker host. you should then see the apps currently playing sound into that pulse server. try and play a sound in openhab and see if a client connects.

if it doesn’t:
Check, if you actually have libpulse-java installed (icedtea). I don't recall if that was necessary.

**Comment by vKnmnn** [comment]
There’s additional info to be found in this topic in the [forum](https://community.openhab.org/t/play-sound-over-standard-java-sinks-via-pulseaudio-to-bluetooth-device/22107/5).

**Comment by angushhz** [comment]
I have encountered problems like this issue. Where can i get ipDockerHost ?
