### ISSUE TITLE
Missing image tags for 2.5.5

### ISSUE THREAD

**Issue by DerOetzi** [openhab/openhab-docker#295]
For version 2.5.5 and 2.5.6-snapshot the architecture specific tags are missing:
 
There should be: 
2.5.5-arm64-alpine
2.5.5-armhf-alpine
2.5.5-amd64-alpine
2.5.5-arm64-debian
2.5.5-armhf-debian
2.5.5-amd64-debian

and same for 2.5.6-snapshot

**Comment by wborn** [comment]
These tags are no longer supported since we switched to BuildKit (https://github.com/openhab/openhab-docker/pull/293). Just remove the architecture from the tags and Docker will figure out itself what image should be downloaded.

**Comment by DerOetzi** [comment]
@wborn thanks for information, then I have to switch my travis build for my openhab_extended as well

**Comment by wborn** [comment]
I hope it's not a big inconvenience. Ever since we've had the multi architecture manifests (https://github.com/openhab/openhab-docker/pull/213) I've tried to minimize the exposure to users of these tags containing the architecture.
