### ISSUE TITLE
Set custom TLS-Certificate

### ISSUE THREAD

**Issue by anionDev** [openhab/openhab-docker#296]
Hello,

i use the (latest) OpenHAB-docker-image and generally it works well. 
But there is one thing i do not understand:
OpenHAB comes with an own selfsigned certificate which is obviously not trusted by any browser. How can i change the TLS-certificate which is used by OpenHAB [jetty]? I have tried every tutorial on the OpenHAB-help-sites and in the community-forum but i can not apply the solutions since in the container i do not have commands like `sudo` or `keytool` (maybe i could install them with `apt` but this is probably not best-pracise) and changing the certificate at runtime in jetty generally seems to be difficult.
So what is the "default-way" or best-practise to set a custom TLS-certificate for OpenHAB when using the OpenHAB-docker-container?

**Comment by wborn** [comment]
I think most users just use a NGINX container as reverse proxy which will then provide SSL and http basic auth to openHAB. That also allows for more easily securing other applications running in containers on the same Docker host.

These support questions are not issues so please ask them in the [community](https://community.openhab.org/) instead.
