### ISSUE TITLE
Snapshot images not available on Docker Hub

### ISSUE THREAD

**Issue by philippwaller** [openhab/openhab-docker#297]
Dear team,

I just noticed that the current snapshot of 2.5.6 is not released on Docker Hub. Can you make it available for testing?

Thanks,
Philipp

**Comment by wborn** [comment]
Yes it's a known issue. For some reason all downloads by Travis CI from `ci.openhab.org` timeout. So it's not possible currently to download the snapshot build and use it for building snapshot images. I entered a support ticket for Travis CI more than a week ago but so far there has been no response/resolution.

**Comment by acidicX** [comment]
@wborn is this also the case for the 2.5.5 armhf alpine image for example? I'm missing this on docker hub as well.

**Comment by wborn** [comment]
> @wborn is this also the case for the 2.5.5 armhf alpine image for example?

Tags containing the architecture are no longer supported, see:
* [Image variants](https://github.com/openhab/openhab-docker#image-variants)
* https://github.com/openhab/openhab-docker/issues/295
* https://github.com/openhab/openhab-docker/pull/293

**Comment by acidicX** [comment]
thx for pointing that out!

**Comment by LukasA83** [comment]
Still no solution?

**Comment by wborn** [comment]
Still no solution. I pinged them again in the support ticket. Maybe it helps. :neutral_face:

**Comment by wborn** [comment]
It looks like Travis CI cannot connect to any IP in the 51.15.x.x address range. I found another user having exactly the same issue since the same day with another host/IP in the same range, see this [Travis community thread](https://travis-ci.community/t/access-to-external-git-repo-not-possible-anymore/8975?u=wborn).

**Comment by wborn** [comment]
I just merged a workaround in https://github.com/openhab/openhab-docker/pull/299 to download the snapshot from the JFrog Maven repo instead of Jenkins.

**Comment by LukasA83** [comment]
Thank you!
