### ISSUE TITLE
Access right problems on Synology

### ISSUE THREAD

**Issue by FrederikNT** [openhab/openhab-docker#300]
Hi,

I am currently running 3.5.6 stable on a Synology. I setup the docker using the Synology UI. Since some time I am getting like every few seconds this meassage within the Synology protocol:
`User [admin] from [my Synology IP adress] failed to log in via [DSM] due to authorization failure.`
After some time the whole Diskstation gets unstable where I even have to reboot it. I was able to track down the login attempt to the openhab docker (admin login attempts stop as soon as I stop the container). I also have other docker container running without having a access right problem.

Openhab itself runs fine within the docker since many months now and I really like it especcially being able to easily update without touching my Synology system. Also now openhab runs just fine beside this spamming of failed admin login attempts.

I tried different UID/GUID combinations as starting paramter, from the standard 9001/9001 to a new created user or even the admin UID/GID without success. I also tried to delete the UID and/or GUI paramater in different combinations without success. This drives me crazy since I can't figure out why the openhab docker container even wants to do something as admin.

Any ideas what to try are really appreatiated since I am running out of them.

NoTechi

**Comment by wborn** [comment]
Maybe it's caused by the [Synology Surveillance Station Binding](https://community.openhab.org/t/binding-request-synology-surveillance-station/8200/386?u=wborn) you seem to be using?
Try uninstalling bindings or disabling rules to see what's causing it.

**Comment by FrederikNT** [comment]
You are right the Surveillance Station Binding was causing it!  Thanks you so much for pointing me in that direction!

NoTechi
