### ISSUE TITLE
network] Include ping and arping in official docker images to avoid unreliable ping

### ISSUE THREAD

**Issue by dafzor** [openhab/openhab-docker#305]
"cross report" of https://github.com/openhab/openhab-addons/issues/8349

When using " network:pingdevice" against a Windows 10 19041.450 PC with latest patches, if the firewall is active with the IMCP Ping inbound rule active, ping tool will be able to ping the PC, but java ping will fail making the device remain offline.

## Expected Behavior
network:pingdevice should be able to ping the PC correctly.

## Current Behavior
network:pingdevice will fail if windows firewall is active with IMCP inbound allowed.

![image](https://user-images.githubusercontent.com/1612206/91347155-c0653880-e7d9-11ea-9f64-b35716c777e1.png)
(gray is no firewall, black shows when firewall is enabled)

This might have been introduced with a recent windows or openHAB update as it was previously working correctly.

## Possible Solution
Installing ping and arping inside the container image and restarting openhab resolves the issue.

## Steps to Reproduce (for Bugs)
1. Have a windows 10 2004 PC with latest patches
2. Have openHAB running on arm docker host
2. enable firewall on windows with default settings and allow core network diagnostics
3. validate ping works by pinging from docker host
4. verify that openHAB does not see device as online
5. disable windows firewall
6. openHAB ping should now work as expected

## Context
It makes it impossible to create rules that depend on computer shutting down.

## Your Environment
* Version used: openHAB 2.5.8
* OS: armbian 10
* Docker: Docker version 19.03.12, build 48a6621
* Hardware: orangePI PC Plus
* network: host has 2 IP assigned to itself (2nd ip is for another container, i did test with the second IP removed with same results)

**Comment by wborn** [comment]
arping is already installed:

https://github.com/openhab/openhab-docker/blob/f16a4ea5908ecbee231cc2bb87c9d9d5885a38f5/2.5.8/debian/Dockerfile#L53-L73

According to the [README](https://github.com/ThomasHabets/arping/blob/arping-2.x/README) it should have more functionality than the `ping` command.

You can install additional packages for your specific use case using a [startup script](https://github.com/openhab/openhab-docker#executing-shell-scripts-before-openhab-is-started) or by building your own container.

**Comment by dafzor** [comment]
I've redeployed the container to re-test the issue, doing so made it pull a new container version and now I'm unable to reproduce it.

No idea what happened as I was able to consistently reproduce the issue and even upgraded from 2.5.7 to 2.5.8 during two days of troubleshooting with both having the same behavior and only fixing itself after I manually installed arping and ping.

**Comment by dafzor** [comment]
And after the previous reply I have seen the issue return after a PC reboot, openhab would not see computer online. Turning off Windows 10 firewall would magically fix it and restarting the openhab container also fixed it...

**Comment by wborn** [comment]
> Installing ping and arping inside the container image and restarting openhab resolves the issue.

> Turning off Windows 10 firewall would magically make online status work again, and restarting the openhab container also fixed it without turning of the firewall...

Let's close this since it doesn't seem like installing ping or arping will solve this as you could fix it by restarting the container. Seems more like some kind of a network/firewall/router issue to me.
