### ISSUE TITLE
Update official docs to explain docker console access

### ISSUE THREAD

**Issue by utdrmac** [openhab/openhab-docker#306]
Currently, on this page: https://www.openhab.org/docs/installation/docker.html, there are no instructions for how to access the console via docker install.

After reading through another PR/Issue, I came across an older path which allowed me to investigate. This appears to be the correct command:

```
$ docker exec -it openhab runtime/bin/client
Logging in as openhab
Password:

                          __  _____    ____
  ____  ____  ___  ____  / / / /   |  / __ )
 / __ \/ __ \/ _ \/ __ \/ /_/ / /| | / __  |
/ /_/ / /_/ /  __/ / / / __  / ___ |/ /_/ /
\____/ .___/\___/_/ /_/_/ /_/_/  |_/_____/
    /_/                        2.5.8
                               Release Build

Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
Hit '<ctrl-d>' or type 'system:shutdown' or 'logout' to shutdown openHAB.

openhab>
```

Please update the docs.

**Comment by wborn** [comment]
It's already documented, see [Accessing the console](https://github.com/openhab/openhab-docker#accessing-the-console).
The docs for your link are maintained [here](https://github.com/openhab/openhab-docs) and not in this repo.
The idea is that those docs get you started and if you want to learn more you read the detailed docs.

**Comment by utdrmac** [comment]
@wborn 

> It's already documented, see [Accessing the console](https://github.com/openhab/openhab-docker#accessing-the-console).

But those docs are incorrect. Accessing `/openhab/runtime/bin/client` results in "file not found". It has to be "runtime/bin/client" as I showed above.

**Comment by wborn** [comment]
Works fine for me:

```
$ docker exec -ti openhab /openhab/runtime/bin/client -p habopen
Logging in as openhab

                          __  _____    ____      
  ____  ____  ___  ____  / / / /   |  / __ )     
 / __ \/ __ \/ _ \/ __ \/ /_/ / /| | / __  | 
/ /_/ / /_/ /  __/ / / / __  / ___ |/ /_/ /      
\____/ .___/\___/_/ /_/_/ /_/_/  |_/_____/     
    /_/                        2.5.8
                               Release Build   

Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
Hit '<ctrl-d>' or type 'system:shutdown' or 'logout' to shutdown openHAB.

openhab> 
```
