### ISSUE TITLE
Make debug level configurable through docker compose

### ISSUE THREAD

**Issue by eschizoid** [openhab/openhab-docker#31]
It will be convenient to have the ability to set the `Karaf` logging level using the `docker-compose` file. That way you don't have to login into the console and execute something like the following:

`log:set TRACE|INFO|DEBUG...`

Or just execute `start_debug.sh` instead of the normal `start.sh`

**Comment by legacycode** [comment]
@kaikreuzer is it possible to set the debug level via command line or environment variable?

**Comment by kaikreuzer** [comment]
No, I don't think so.

**Comment by cyberkov** [comment]
So it is a "wontfix". The call to the debug script is within the entrypoint already (in docker-compose you would use `command: debug`). Closing.
