### ISSUE TITLE
[Help] Location of webapps folder

### ISSUE THREAD

**Issue by tmp-hallenser** [openhab/openhab-docker#312]
Hi,

Where is the `webapps` folder located, e.g. mentioned here: https://www.openhab.org/addons/bindings/weather1/#html-layouts ?

The folder `var/lib/openhab2/webapps/` doesn't exist.

I'm using the latest image on armv7 architecture.

**Comment by wborn** [comment]
The file locations inside the container are similar to that of a manual setup but with `/openhab` as base directory.
See these [File Locations](https://www.openhab.org/docs/installation/linux.html#file-locations). So you can probably use: `/openhab/userdata/webapps`
