### ISSUE TITLE
Fix automatic builds

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-docker#318]
Currently Travis CI will not automatically build the Docker images because the default OSS credits have been exhausted due to their [new pricing model](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing).

There are several ways to fix it:

* Request for an increase of the Travis CI OSS allotment
* Move builds to Docker Hub automated builds
* Move builds to the openHAB Jenkins instance
* Move builds to GitHub actions

Until there's a solution I'll resort to pushing the images manually to Docker Hub from time to time.

**Comment by kuifje123** [comment]
@wborn I notice that you have updated the M4 image to docker hub.
Could you also update the snapshot images?
Thanks!

**Comment by wborn** [comment]
Yes I'm planning to do that too today after there is a recent  add-ons/distro build so it has everything thats also in the M4. :-)

**Comment by wborn** [comment]
After exploring all the options I'll move official builds to the openHAB Jenkins instance and will most likely switch to GitHub Actions for PR builds.

Since today there is a working Jenkins build job for automatically building the 3.0.0 snapshot images whenever there's a new snapshot distro build. :-)
