### ISSUE TITLE
Cannot exec console

### ISSUE THREAD

**Issue by kceiw** [openhab/openhab-docker#33]
I follow the documentation to run docker image.

> docker run \
>         --name openhab \
>         --net=host \
>         -v /etc/localtime:/etc/localtime:ro \
>         -v /etc/timezone:/etc/timezone:ro \
>         -v /opt/openhab/conf:/openhab/conf \
>         -v /opt/openhab/userdata:/openhab/userdata \
>         -d \
>         --restart=always \
>         openhab/openhab:amd64-online

And then tried to access the console
> docker exec -it openhab console

I get this error

> rpc error: code = 2 desc = "oci runtime error: exec failed: exec: \"console\": executable file not found in $PATH"openhab $ 

I run 
>docker exec -it openhab sh

and don't find console in /bin/, /usr/bin, /sbin, or /usr/sbin.

Shouldn't the image be set up with right PATH?

**Comment by eschizoid** [comment]
@kceiw There is a PR open for this repo that has a more up to date documentation. For the time being please read this:

https://github.com/openhab/openhab-docs/blob/gh-pages/installation/docker.md
