### ISSUE TITLE
Tags for major versions

### ISSUE THREAD

**Issue by linus-ha** [openhab/openhab-docker#333]
Please add image tags for major versions like: `openhab:2, openhab:3, openhab:2-alpine` ...

Would be great for the transition from openHAB v2 to v3.

**Comment by wborn** [comment]
I wouldn't use any rolling tag in production, knowing that OH may introduce major breaking changes at any time in newer 2.x (or 3.x) releases. :wink:

**Comment by wborn** [comment]
I still don't think it is a good idea to use rolling tags for major release versions in production.

**Comment by theKBro** [comment]
Why is that the case? If semantic versioning is used I see no problem there.
In particular versions that only differ in 'patch' should not be incompatible.
Currently I have to pull the docker hub to see if there is a new version of the openhab images.
If you would provide images with tags e.g. `openhab:4` or `openhab:4.0` a watchtower instance could simply notify me about a new version or even update it by itself.

> I still don't think it is a good idea to use rolling tags for major release versions in production.

I would also never use rolling major tags for production, but like it is now you aren't even allowing rolling minor or patch updates.
