### ISSUE TITLE
Unable to override -Xmx

### ISSUE THREAD

**Issue by Gibby** [openhab/openhab-docker#34]
Tried a few different environment variables but unable to override -Xmx. Looks like it is hard coded in /openhab/runtime/karaf/bin/setenv on line 86.

**Comment by cniweb** [comment]
Hi @Gibby 

I think, this is not a openhab-docker problem!
@kaikreuzer is it a general openHAB2 problem?

Chris

**Comment by kaikreuzer** [comment]
It is indeed defined in https://github.com/openhab/openhab-distro/blob/master/distributions/distribution-resources/src/main/resources/bin/setenv#L86.
Afaik, 256MB is the default, so it should be safe to remove it from there.
@Gibby Would you want to create a PR with this change for both setenv.sh and setenv?

**Comment by Gibby** [comment]
@kaikreuzer 
Created https://github.com/openhab/openhab-distro/pull/304

**Comment by kaikreuzer** [comment]
Perfect, thanks. Already merged.
