### ISSUE TITLE
arm/v7 is missing in the alpine builds

### ISSUE THREAD

**Issue by acidicX** [openhab/openhab-docker#340]
Hi,

I noticed that compared to v2 builds, the v3 builds are missing the arm/v7 build for alpine.
I'm using it on a RBPi so I'd prefer to use a slim image like alpine instead of Debian.

I've looked through the build scripts but can't really pinpoint the problem. Let me know if I can help anyhow.

**Comment by wborn** [comment]
It's an Alpine issue. They don't have an openjdk11 package for ARMv7.

See: https://gitlab.alpinelinux.org/alpine/aports/-/issues/11229

This is also documented in the [README](https://github.com/openhab/openhab-docker#image-variants):

> There is no linux/arm/v7 Alpine image for openHAB 3 because the openjdk11 package is unavailable for this platform.
