### ISSUE TITLE
stderr is flooded with a lot of debug logs

### ISSUE THREAD

**Issue by HolgerHees** [openhab/openhab-docker#346]
I use docker with jounald integration and now, everytime I restart the container, my logs are flooded with error logs which should be debug logs printed out to stdout

I think, the reason is that the entrypoint bash skript is started in trace mode (bash -x). Can we make this behavior configurable via env variables?

**Comment by wborn** [comment]
What debug logging do you see?

**Comment by HolgerHees** [comment]
I see all shell commands printed out to stderr before they are executed.
This is a behavior that happens if you run bash shell in trace mode.

Am Mi., 20. Jan. 2021 um 09:19 Uhr schrieb Wouter Born <
notifications@github.com>:

**Comment by wborn** [comment]
Yes it helps with troubleshooting issues for newbies. But maybe we can add an option to suppress it for more experienced users. 

Adding an option for skipping the ownership changes is also on my todo list as it may not always be useful and also takes a lot of time when starting the containers on SBCs with slow storage.
