### ISSUE TITLE
Badges broken on front page

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-docker#35]
There are a few broken images for the badges on the README.md, see:

![bildschirmfoto 2016-09-30 um 09 48 49](https://cloud.githubusercontent.com/assets/3244965/18984492/3996e1a0-86f3-11e6-84c5-7a24fca6f0b2.png)

**Comment by cniweb** [comment]
Hi @kaikreuzer 

issuestats.com badges works!
See: http://www.issuestats.com/github/openhab/openhab-docker
imagelayers.io badge are broken, the docker api call is wrong.
See: https://imagelayers.io/?images=openhab%2Fopenhab:latest
Should I remove the badge?

Chris

**Comment by kaikreuzer** [comment]
> issuestats.com badges works!

Then the README.md seems to contain a bad link.

> Should I remove the badge? 
Well, yes, any broken badge on the frontpage that cannot be fixed should be removed.
