### ISSUE TITLE
Include ffmpeg

### ISSUE THREAD

**Issue by rueckix** [openhab/openhab-docker#358]
## Summary
Include ffmpeg and its dependencies in the docker images

## Expected Behavior
Users of the ipcamera addon should be able to simply install from the UI and use all addon features.

## Current Behavior
Users of the ipcamera addon will have to manually add ffmpeg `sudo apt update && sudo apt install -yy ffmpeg` in their docker containers. This step has to be repeated with every container update.

## Possible Solution
Include ffmpeg in the Dockerfile via apt/apt.

### Image
openhab/openhab:latest

**Comment by wborn** [comment]
Sorry, installing it will increase the image size by 85MB.
See [Missing some preinstalled package](https://github.com/openhab/openhab-docker#missing-some-preinstalled-package).

**Comment by rueckix** [comment]
Thanks for the prompt response. Script solution will work in my case, I guess.
