### ISSUE TITLE
docker image does not include ffmpeg which is mandatory for ipcamera binding

### ISSUE THREAD

**Issue by viknet365** [openhab/openhab-docker#361]
The solution I found is quite simple: apt-get update and apt-get install ffmpeg
also it make the image bigger....
Any other solution to use the camera binding in the docker is welcome......

**Comment by wborn** [comment]
See https://github.com/openhab/openhab-docker/issues/358

**Comment by viknet365** [comment]
@wborn sorry for the duplicate !!  thanks for clarifying (even if the answer is disappointing.)
