### ISSUE TITLE
GROUP_ID must not be 997

### ISSUE THREAD

**Issue by 36grad** [openhab/openhab-docker#362]
The chapter [User and group identifiers](https://github.com/openhab/openhab-docker#user-and-group-identifiers) describes two methods to sync the user inside the container with the user on the docker host.
However, when using the second method (provide user and group id of existing user to the container) then the container will crash if the group ID equals 997.

It should be somehow documented that the group ID 997 is already used by the container internally (something with gpio...) and thus must not be used on the docker host system for the openhab user.

**Comment by wborn** [comment]
I'd rather not add all these OS specific implementation details to the container docs.

Just read the docs of the base container OS next time:

https://www.debian.org/doc/manuals/system-administrator/ch-sysadmin-users.html

> UIDs 0-99 are globally allocated by the Debian project and are used for system accounts. The "root" account, for instance, is UID 0.
> UIDs 100-999 are for system users which have not been allocated by the Debian project.
> UIDs 1000-29999 are normal user accounts.

So it is best to avoid using any ID < 1000
