### ISSUE TITLE
Error Starting container OpenJDK Client VM warning: No monotonic clock was available 

### ISSUE THREAD

**Issue by Rathna-K** [openhab/openhab-docker#370]
posted this in the community as well but have not received a response so trying my luck here. looks like the JDK in the 3.2.0 snapshot build has some issues and I see this error  in the docker logs and container keeps reporting the status as Starting. the openhab endpoint is not available as well. openhab.log seems to be empty as well. 

here are the issue details : 

Raspberry Pi 4, Docker Engine - 20.10.10
openhab:3.2.0-snapshot
as the title suggest, I just pulled the latest 3.2.0-snapshot and when I start the openhab I am getting this entry and the container state is either stuck at "starting" or "unhealthy". not sure if that JDK error is the issue or not. any thoughts? 

```yaml
Launching the openHAB runtime...
OpenJDK Client VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
```

please see this link for reference : https://stackoverflow.com/questions/67346333/how-to-solve-gradle-docker-image-freezing-on-raspberry-pi-with-warning-about-mon

https://community.openhab.org/t/docker-openhab-3-2-0-snapshot-stuck-at-unhealthy-with-openjdk-client-vm-warning-no-monotonic-clock-was-available/128865

**Comment by wborn** [comment]
As already pointed out in the community, this is an issue which you should resolve on your Docker host by upgrading libseccomp so it can properly handle newer/unknown system calls made by Docker containers.

If you cannot upgrade it you can also disable seccomp, but that of course makes your system less secure, see: https://docs.docker.com/engine/security/seccomp/
