### ISSUE TITLE
HABPanel configuration lost when container is deleted

### ISSUE THREAD

**Issue by tkosig** [openhab/openhab-docker#38]
I'm not sure whether this issue applies to the docker container or OpenHAB directly. I've updated my image for OpenHAB today and due to having to use a 3rd party GUI (Synology) I end up deleting the container, updating the image and then creating a new container with the same settings.

For the container I've mounted /openhab/conf and /openhab/userdata to folders in my host's filesystem.

After updating the container I've noticed that my HABPanel configuration is gone. HABPanel pulls it's configuration from <openHAB url>/rest/services/org.openhab.ui.habpanel/config

Wherever that data is stored I assume it is not in the _userdata_ or _conf_ directories since the configuration is gone after my update. I would propose for that information to be stored in _userdata_ or if it is stored in another directory to update the instructions for this image so that the users persist the path where it is stored to the host's filesystem.

**Comment by jmccoy555** [comment]
I think this was moved in the latest version.

**Comment by legacycode** [comment]
@tkosig is this issue still relevant or can we close it?
