### ISSUE TITLE
installing habmin

### ISSUE THREAD

**Issue by snizzleorg** [openhab/openhab-docker#4]
What is the default way to get habmin running in the docker container?

**Comment by kaikreuzer** [comment]
Waiting until it is part of the openHAB Distribution ;-)

**Comment by snizzleorg** [comment]
hm. the container install is working really nice so far. however I'm struggling to configure all the items since the paperUi does not support that - right?

**Comment by cyberkov** [comment]
@snizzleorg in the meantime you can download the Habmin Jar and create a hostvolume for ``/openhab/addons``.
You can have a look at my [Makefile](https://github.com/cyberkov/my-openhab-config/blob/master/Makefile#L16) for reference :)
