### ISSUE TITLE
Release 4.2.3 is missing

### ISSUE THREAD

**Issue by Novanic** [openhab/openhab-docker#448]
Hello, could you please release the new version 4.2.3 on Docker Hub? The documentation and download link are already updated, but the release and tag is missing.

Thank you and best regards

**Comment by wborn** [comment]
Looks like the [release build got aborted](https://ci.openhab.org/view/Release%20Jobs/job/openhab-patch-release/49/) in the last step which may explain why the 4.2.3 Docker images were not build. I just triggered the Docker build manually so the 4.2.3 images are available now.
