### ISSUE TITLE
Error on Docker Cloud

### ISSUE THREAD

**Issue by cniweb** [openhab/openhab-docker#5]
I use the https://cloud.docker.com platform to try the image.
After the start of the service the following error message appears in the log:
`cniweb-openhab-1 | 2016-04-06T19:25:44.969654500Z + set -euo pipefail`
`cniweb-openhab-1 | 2016-04-06T19:25:44.969743100Z + IFS='`
`cniweb-openhab-1 | 2016-04-06T19:25:44.970312700Z  '`
`cniweb-openhab-1 | 2016-04-06T19:25:44.987670200Z ++ ls -A /openhab/userdata`
`cniweb-openhab-1 | 2016-04-06T19:25:44.988569000Z + '[' -z 'deploy`
`cniweb-openhab-1 | 2016-04-06T19:25:44.988585100Z etc`
`cniweb-openhab-1 | 2016-04-06T19:25:44.988594400Z logs`
`cniweb-openhab-1 | 2016-04-06T19:25:44.988599100Z tmp' ']'`
`cniweb-openhab-1 | 2016-04-06T19:25:44.988604700Z ++ ls -A /openhab/conf`
`cniweb-openhab-1 | 2016-04-06T19:25:44.988808000Z + '[' -z '' ']'`
`cniweb-openhab-1 | 2016-04-06T19:25:44.988897400Z + echo 'No configuration found... initializing.'`
`cniweb-openhab-1 | 2016-04-06T19:25:44.989008400Z No configuration found... initializing.`
`cniweb-openhab-1 | 2016-04-06T19:25:45.007131600Z + sudo cp -av '/openhab/conf.dist/. /openhab/conf/'`
`cniweb-openhab-1 | 2016-04-06T19:25:45.018393400Z cp: missing destination file operand after '/openhab/conf.dist/. /openhab/conf/'`
`cniweb-openhab-1 | 2016-04-06T19:25:45.019273700Z Try 'cp --help' for more information.`

**Comment by cyberkov** [comment]
Hello!
Classic typo :) I updated the entrypoint and it should populate the /openhab/config directory as well.

Cheers
Hannes

**Comment by cniweb** [comment]
Hi Hannes,
OK, a another try...
After the start of the service the following error message appears in the log:
`cniweb-openhab-1 | 2016-04-06T22:18:24.956502700Z + set -euo pipefail`
`cniweb-openhab-1 | 2016-04-06T22:18:24.956546900Z + IFS='`
`cniweb-openhab-1 | 2016-04-06T22:18:24.956552100Z  '`
`cniweb-openhab-1 | 2016-04-06T22:18:24.956556600Z ++ ls -A /openhab/userdata`
`cniweb-openhab-1 | 2016-04-06T22:18:24.966412200Z + '[' -z 'deploy`
`cniweb-openhab-1 | 2016-04-06T22:18:24.966427200Z etc`
`cniweb-openhab-1 | 2016-04-06T22:18:24.966439400Z logs`
`cniweb-openhab-1 | 2016-04-06T22:18:24.966443400Z tmp' ']'`
`cniweb-openhab-1 | 2016-04-06T22:18:24.966447200Z ++ ls -A /openhab/conf`
`cniweb-openhab-1 | 2016-04-06T22:18:24.967002100Z + '[' -z 'html`
`cniweb-openhab-1 | 2016-04-06T22:18:24.967013900Z items`
`cniweb-openhab-1 | 2016-04-06T22:18:24.967018300Z persistence`
`cniweb-openhab-1 | 2016-04-06T22:18:24.967022300Z rules`
`cniweb-openhab-1 | 2016-04-06T22:18:24.967026200Z scripts`
`cniweb-openhab-1 | 2016-04-06T22:18:24.967030100Z services`
`cniweb-openhab-1 | 2016-04-06T22:18:24.967034000Z sitemaps`
`cniweb-openhab-1 | 2016-04-06T22:18:24.967037800Z things`
`cniweb-openhab-1 | 2016-04-06T22:18:24.967114300Z transform' ']'`
`cniweb-openhab-1 | 2016-04-06T22:18:24.967147500Z + '[' /bin/sh = server ']'`
`cniweb-openhab-1 | 2016-04-06T22:18:24.967174000Z + '[' /bin/sh = openhab ']'`
`cniweb-openhab-1 | 2016-04-06T22:18:24.967203200Z + '[' /bin/sh = debug ']'`
`cniweb-openhab-1 | 2016-04-06T22:18:24.967799800Z + exec /bin/sh -c server`
`cniweb-openhab-1 | 2016-04-06T22:18:24.968077600Z /bin/sh: 1: server: not found`

Can you help?

Thanks,
Chris

**Comment by cyberkov** [comment]
Hello @cniweb !

Can you please check your ``command`` in the cloud?
The entrypoint script knows [4 different commands](https://github.com/openhab/openhab-docker/blob/master/files/entrypoint.sh#L19) that can be passed:

- ``openhab`` (alias for ``server``)
- ``server``
- ``debug``
- everything else ( will be executed through bash)

In your case the command seems to be ``/bin/sh -c server`` which would cause to fall into the fourth case.
You might also want to try ``/openhab/start.sh`` as command. I guess this will work.

Cheers
Hannes

**Comment by cniweb** [comment]
Hello @cyberkov,

in my case, the command `/bin/sh -c server` is defined in image!
If I set `/openhab/start.sh` as command, then it works.
Should we then not as the default command in the image?

Chris

**Comment by cyberkov** [comment]
Hello @cniweb! 
I built a new image with a different CMD command and i think this should resolve this issue. Can you please test ``cyberkov/openhab2:cmdtest`` if this works?

Thanks in advance!
Cheers
Hannes

**Comment by cniweb** [comment]
Hi @cyberkov,

the "Run command" = server (defined in image).
See: https://github.com/cyberkov/openhab-docker/blob/fix-cmd-command/Dockerfile#L56

Chris

**Comment by cyberkov** [comment]
There is a slight difference between calling the command in in brackets and the call without these (it is passed to "sh - c"  then) and I think this might cause this. I will make a PR tomorrow. 
Cheers Hannes

**Comment by marnikvde** [comment]
I can confirm that replacing "CMD server" with "CMD  ["server"]" works

**Comment by cniweb** [comment]
I can confirm it, too.

Thanks @cyberkov
