### ISSUE TITLE
docker image tags are confusing - document flavours

### ISSUE THREAD

**Issue by ssbarnea** [openhab/openhab-docker#50]
It seems that the tag names are confusing and not documented. What is the difference between: simple `amd64`, `amd64-online` and `amd64-offline`?

Also, clearly less important, is the fact that I find the use of `amd64` near `arm64` only making harder to figure-out the correct tag, probably I would have prefered a more popular platform identifier like `x64` (seems to be the most popular based on google search). Many people do not know that `amd64` is synonym with `x86-64`, `x64` or `x86_64`.

**Comment by legacycode** [comment]
Hi! You are very fast. The flavors were removed today and the documentation was updated with pull request #48 a few hours ago. You can find more details in #44. You can find the actual documentation in this master. I think that the maintainer will update the documentation on dockerhub soon.

For cross compiling, this project uses the containers from multiarch/debian-debootstrap and the archtype ``amd64`` represents the docker tag from that image. You can find a list at (https://hub.docker.com/r/multiarch/debian-debootstrap/tags/).

I will update the documentation in the next days and make some additional notes to ``amd64``.

**Comment by legacycode** [comment]
You can close this issue after merging PR #51
