### ISSUE TITLE
failed switching to "openhab": operation not permitted

### ISSUE THREAD

**Issue by deradam** [openhab/openhab-docker#55]
I followed the guide here: http://docs.openhab.org/installation/docker.html#running-the-container-as-a-service-managed-by-docker

However I did not succeed. I always get the following error at the end of the startup process and then it stops:

+ gosu openhab /openhab/start.sh
error: failed switching to "openhab": operation not permitted

Ubuntu 16.10, AMD64.

**Comment by legacycode** [comment]
I think it is a permission problem with your docker mount point. Could you please try the following command to check, if openhab starts correctly?

```
docker run \
        --name openhab \
        --net=host \
        -v /etc/localtime:/etc/localtime:ro \
        -v /etc/timezone:/etc/timezone:ro \
        -v /openhab/conf \
        -v /openhab/userdata \
        -d \
        --restart=always \
        openhab/openhab:amd64
```
Please let me know, what command you use to run the container.

Best regards.

**Comment by deradam** [comment]
@legacycode yep, you are right. Without the user parameter and the changed volumes it is starting up:

gosu openhab /openhab/start.sh
Launching the openHAB runtime...

                          __  _____    ____      
  ____  ____  ___  ____  / / / /   |  / __ )     
 / __ \/ __ \/ _ \/ __ \/ /_/ / /| | / __  | 
/ /_/ / /_/ /  __/ / / / __  / ___ |/ /_/ /      
\____/ .___/\___/_/ /_/_/ /_/_/  |_/_____/     
    /_/                        2.0.0
                               Release Build   

I started it with the following command: `
docker run --name openhab --net=host --pid=host -v /etc/localtime:/etc/localtime:ro -v /etc/timezone:/etc/timezone:ro -v /opt/openhab/conf:/openhab/conf -v /opt/openhab/userdata:/openhab/userdata -v /opt/openhab/addons:/openhab/addons --user=999 --it openhab/openhab:amd64`

The directory structure is as follows:

hub:/opt/openhab$ ls -la
total 20
drwxr-xr-x  5 openhab openhab 4096 Jan 24 21:32 .
drwxr-xr-x  3 root    root    4096 Jan 24 21:06 ..
drwxr-xr-x  2 openhab openhab 4096 Jan 24 21:06 addons
drwxr-xr-x 13 openhab openhab 4096 Jan 24 00:19 conf
drwxr-xr-x  4 openhab openhab 4096 Jan 25 23:00 userdata

hub:/opt/openhab$ id openhab
uid=999(openhab) gid=999(openhab) groups=999(openhab)

As I said, according to the manual.

Thanks for your support.

**Comment by legacycode** [comment]
At the moment it is not possible to set the user id via a run command. The openhab user in this image uses uid 1000. Could you please try to change to that user id. chown your directory to 1000 and let me know if it works.

**Comment by Nzbuu** [comment]
Looks like 1000 is the uid of the `pi` user in raspbian, so that's probably a poor choice.

**Comment by legacycode** [comment]
1000 is alway the first user created by the system. I implemented the possibility to change the USER_ID with #61. That makes it easier to set a custom UID to the openhab user.

**Comment by cniweb** [comment]
Hi @legacycode,

can you check the OH Docs for docker:
https://github.com/openhab/openhab-docs/blob/gh-pages/installation/docker.md

I think the `-v /opt/openhab/addons:/openhab/addons\` section is wrong, or?
And change the new usage, please. 

Thanks,
Chris

**Comment by legacycode** [comment]
@cniweb we should not mix up the topics. can we discuss the documentation requirement in a new thread?

@deradam do you still need support or did my last commit #61 solved your issue?

**Comment by legacycode** [comment]
i updeated the documentation to start with docker named values instead of mounting points. pls refer to PR #62. After merging this issue can be closed.

**Comment by deradam** [comment]
@legacycode thanks for fixing and clarification. It works for now with chown 1000 - which is indeed my main user.
