### ISSUE TITLE
OPENHAB_HTTP_PORT and OPENHAB_HTTPS_PORT are ignored

### ISSUE THREAD

**Issue by henfri** [openhab/openhab-docker#64]
Hello,

I have services running on Port 8080 already. Thus, I need to change the OPENHAB_HTTP_PORT.
This does not work though:

> openhab:
>   image: "openhab/openhab:2.0.0-amd64"
>   restart: always
>   net: host
>   volumes:
>     - "/etc/localtime:/etc/localtime:ro"
>     - "/etc/timezone:/etc/timezone:ro"
>     - "/srv/Daten/dockerconfig/knx/openhab/userdata:/openhab/userdata"
>     - "/srv/Daten/dockerconfig/knx/openhab/conf:/openhab/conf"
>   environment:
>     OPENHAB_HTTP_PORT: "8082"
>     OPENHAB_HTTPS_PORT: "8444"

Still OpenHAB tries to bind to 8080.

Looking at the entrypoint.sh I don not see that these Variables are used as well (I would expect them to be passed to the executable when launched).

**Comment by henfri** [comment]
I think, the reason is, that OpenHAB nows the variable:
HTTP_PORT
and 
HTTPS_PORT

Whereas the documentation on docker-hub says:
OPENHAB_HTTP_PORT and OPENHAB_HTTPS_PORT

With HTTP_PORT it does seem to work here.

**Comment by kaikreuzer** [comment]
OPENHAB_* are the correct variables, see the official docs: http://docs.openhab.org/installation/security.html#webserver-ports

FTR, there is a similar issue report for the apt package: https://github.com/openhab/openhab-linuxpkg/issues/23

**Comment by henfri** [comment]
Interesting...

It's a bit odd:

> root@homeserver:~/Docker/knx-ng# docker-compose config |grep -i port
>       HTTPS_PORT: '8444'
>       HTTP_PORT: '8082'

So, in the configuration file, i omit the OPENHAB_

Whereas on
> root@homeserver:~/Docker/knx-ng# docker inspect f0af872de4cd | grep -i port
>                 "OPENHAB_HTTPS_PORT=8444",
>                 "OPENHAB_HTTP_PORT=8082",

So, the container seems to be running *with* OPENHAB_...
Thus, I am not sure whether what I stated above (i.e. it does work *without* OPENHAB_...) is correct.

**Comment by legacycode** [comment]
hi. i have tried your example and it binds correctly to port 8082 with OPENHAB_HTTPS_PORT on my system. On my second system it is also working.

```
Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

docker-compose version 1.9.0, build 2585387
docker-py version: 1.10.6
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Comment by henfri** [comment]
Hello,

as I cannot reproduce this myself anymore, I propose to close this. Sorry about the confusion.

Regards,
Hendrik

**Comment by legacycode** [comment]
You are welcome :-)

**Comment by henfri** [comment]
... and thank you.
Sorry for being inpolite!
