### ISSUE TITLE
Add some more configuration options

### ISSUE THREAD

**Issue by thucke** [openhab/openhab-docker#65]
I'm missing the possibility to change LOCALE settings of of the container to `de_DE.utf8` via ENV-direction.
Please activate all locales in `/etc/locale.gen` and activate them via `locale-gen`.

I'm running the container on a Synology NAS. If I try to add `--user=1031`, which ist the UID of the openhab user on the NAS the container would not start. The default user configuration uses UID=GID=1000. Running with --user-directive an error occurs that gosu no permission (or something like this). 
It would be great if we could provide the UID and GID of the containers user configuration vie ENV-direction.

**Comment by cniweb** [comment]
`USER_ID` is available since version 2.1.0-snapshot

**Comment by legacycode** [comment]
USER_ID is now also available in version 2.0.0

**Comment by legacycode** [comment]
This one can be closed.
