### ISSUE TITLE
wrong permissions for pax-web-api-4.3.0.jar 

### ISSUE THREAD

**Issue by kopfpilot** [openhab/openhab-docker#72]
It is not possible to successfully start openhab if the USER_ID env variable is set to something else then 9001.

The file /openhab/runtime/system/org/ops4j/pax/web/pax-web-api/4.3.0/pax-web-api-4.3.0.jar is owned by the user openhab (userid = 9001) and the permssions are set to 600.

Openhab would start with a different USER_ID if the permissions would be set to 666.

**Comment by legacycode** [comment]
Yeah... you are right and i found the probelm. The user is generated in the Dockerfile when the image is build. It needs to be in an entrypoint.sh file to work correct. I will change this next week.

**Comment by legacycode** [comment]
#71 seems to be the same problem.

**Comment by kopfpilot** [comment]
Issue #71 is more like a follow up problem someone would have, if pax-web-api-4.3.0.jar would be readable for other USER_IDs.

Did you ever consider to use s6-overlay for preparation tasks like adding a group and user, changing file ownership and starting the application with the new user? You might want to take a look at what linuxserver.io does in their images.

**Comment by kopfpilot** [comment]
sorry accidently close.
