### ISSUE TITLE
Charts not working with oh2 docker version

### ISSUE THREAD

**Issue by harrzz** [openhab/openhab-docker#73]
Hallo, 

the chart drawing is broken since openhab 2.0.0 release.

I have tested it with both docker  images 2.0.0 and the 2.1.0-snapshot.
I have also build the docker image by myself using the dockerfile from the repository.
After creating each docker container I have copied the initial config files for "userdata" and "conf" from the dist directory as discribed in the readme.

On the demo sitemap in the weather section the empty image for the chart is not generated!

In the openhab.log the following error occurs:
` [eclipse.jetty.servlet.ServletHandler] - Error for /chart
java.lang.Error: Probable fatal error:No fonts found.`

[openhab.log.txt](https://github.com/openhab/openhab-docker/files/753292/openhab.log.txt)

**Comment by harrzz** [comment]
It seems that this issue is caused by the Zulu openJDK. I used the original openhab2 Dockerfile and replaced the base docker image by the openjdk:8 image and commented out the Zulu openJDK installtion part. With this build of the openhab2 docker container everything is working fine. 

I'm fine with this solution. It solves my problems. 
Maybe it's an hint for you to fix the openhab2 docker image with a newer version of the Zulu openJDK.

**Comment by cniweb** [comment]
Maybe it would be a way to support both JDKs? So long until zulu works correctly. Possibly with separate tags?

**Comment by e10kstarfire** [comment]
So glad I found this issue posted, I have exactly the same issue with the fonts message.

Do we know when this will be fixed as none of my charts have been working for some time ?

**Comment by harrzz** [comment]
From my opinion, it would be a good solution to support both JDK's @cniweb 

@e10kstarfire until there is no official decision/fix from the openHAB team you can go with the modified Dockerfile of mine: [https://github.com/harrzz/openhab-docker/blob/master/2.0.0/amd64/Dockerfile](url)

**Comment by kaikreuzer** [comment]
> Maybe it would be a way to support both JDKs? 

Well, moving away from OracleJDK [had a reason](https://blog.takipi.com/running-java-on-docker-youre-breaking-the-law/). So I would very much prefer to analyse the issue and find a solution for it. A "font not found" sounds as if it might just be some configuration that needs to be set.

**Comment by kaikreuzer** [comment]
Note that we are also moving openHABian and others to Zulu JDK, so if there is a problem, we need to look at it anyhow. The docker image should follow the same recommendations.

**Comment by harrzz** [comment]
> Well, moving away from OracleJDK had a reason. 
I don't know about this. Good to know, thanks for the hint.

I even don't know about Zulu JDK until I had looked into the Dockerfile from openHAB.
I totally agree with you @kaikreuzer  to solve the issue with Zulu JDK is the better solution.

**Comment by kaikreuzer** [comment]
> so if there is a problem, we need to look at it anyhow

Hm, it seems this is a general problem: https://github.com/openhab/openhab-distro/issues/421
Does anyone have an idea how to solve this?

**Comment by nesys** [comment]
Hi folks, I have the same issue on openhabian 2.5.0~S1731-1 (Build #1731)

case: https://github.com/openhab/openhabian/issues/748
