### ISSUE TITLE
Problems with permissions (uid 9001)

### ISSUE THREAD

**Issue by Wurzelseppi** [openhab/openhab-docker#77]
Hi,

I´m aware ofo the fact, that I´m not the first one, but I didn´t encouter this one whilst searching :+1: 
When I start the docker i get this failure (I can´t set the uid of my user on Synology NAS, so i have to inject my own user with -u option)

docker run   -u 1035  --name openhab  --net=host   -v /etc/localtime:/etc/localtime:ro  -v /volume1/Synology-Infrastructure/openHAB2/addons:/openhab/addons   -v /volume1/Synology-Infrastructure/openHAB2/conf:/openhab/conf   -v /volume1/Synology-Infrastructure/openHAB2/userdata:/openhab/userdata   5ad8888d9abb
Launching the openHAB runtime...
Unable to update instance pid: Unable to create directory /openhab/runtime/instances

**Comment by legacycode** [comment]
Hi,

could you please try running the last build again. Remove the -u paramater and replace it by -e USER_ID=1035:

docker run -e USER_ID=1035 --name openhab --net=host -v /etc/localtime:/etc/localtime:ro -v /volume1/Synology-Infrastructure/openHAB2/addons:/openhab/addons -v /volume1/Synology-Infrastructure/openHAB2/conf:/openhab/conf -v /volume1/Synology-Infrastructure/openHAB2/userdata:/openhab/userdata openhab/openhab:<version>-<architecture>

**Comment by Wurzelseppi** [comment]
Working now .! ... Thanks

**Comment by cniweb** [comment]
Do we need to document something more?

**Comment by legacycode** [comment]
yeah. i am still working on the documentation and will create a pull request in a few minutes.

**Comment by legacycode** [comment]
pls close this issue.
