### ISSUE TITLE
Timezone/Localtime: cannot mount volume over existing file, file exists

### ISSUE THREAD

**Issue by dhermanns** [openhab/openhab-docker#78]
It seems to me that the image openhab/openhab            2.0.0-armhf has a problem.
 
When I try to mount I got:
`cannot mount volume over existing file, file exists /var/lib/docker/devicemapper/mnt/a7818c9c114993726bfa4bd352a5e2aea2fa007738a42b2495962d2daa7b0bb6/rootfs/etc/localtime
`
It looks like there is already a UTC timezone/localtime existing, so I can't mount my own settings.

**Comment by legacycode** [comment]
It seems that you are declaring the file and not mounting it. Could you please provide yout full run/compose command?

**Comment by dhermanns** [comment]
Thanks for the reply. Here is my docker-compose.yml:

`openhab2:
  image: 'openhab/openhab:2.0.0-armhf'
  restart: always
  ports:
    - "8101:8101"
    - "8080:8080"
    - "8443:8443"
    - "5555:5555"
    - "9124:9124"
  net: "host"
  volumes:
    - '/home/pi/openhab2/conf:/openhab/conf'
    - '/home/pi/openhab2/userdata:/openhab/userdata'
    - '/etc/localtime:/etc/localtime:ro'
    - '/etc/timezone:/etc/timezone:ro'
  command: "server"`

I launch with:
`docker-compose up -d`

**Comment by legacycode** [comment]
Hmmm... I cant find a problem in the armhf version. Are you using a different docker storage driver? Could you please tell me more about your hardware, operating system and docker version? Could you maybe reinstall your system to check, if the error still exists?

**Comment by dhermanns** [comment]
Im using a Pi3 with raspbian OS. I could test this again on a Pi2.

legacycode <notifications@github.com> schrieb am Di., 14. Feb. 2017, 20:59:

**Comment by dhermanns** [comment]
I tested it on my Pi2 with docker 1.6. Same problem there:

```
$ docker-compose up
Recreating openhab2_openhab2_1...
file exists at /var/lib/docker/overlay/1e80b603e4e8e8adc6d1778c6811f0ccbba4d9208a853640a471755475bedb9a/merged/etc/localtime, can't create volume there
```

**Comment by dhermanns** [comment]
Regarding to this [ticket](https://github.com/jwilder/nginx-proxy/issues/141) it should be an issue with docker-compose. I was running on a pretty old version 1.1.0. I updated to 1.9.0 and the mounting worked like a charme afterwards ;-) . Thanks for your great work.
