### ISSUE TITLE
Build broken since #481

### ISSUE THREAD

**Issue by RyanRamchandar** [openhab/openhab-docker#79]
https://openhab.ci.cloudbees.com/job/openHAB2-Docker/

**Comment by cniweb** [comment]
The Travis CI build job is actually the relevant one.
https://travis-ci.org/openhab/openhab-docker

**Comment by RyanRamchandar** [comment]
@cniweb ah got it. Bit confusing to have two running.

**Comment by legacycode** [comment]
What is that for a build? Can it be deleted?

**Comment by cniweb** [comment]
I guess so.
@kaikreuzer Who created it and can delete it?

**Comment by kaikreuzer** [comment]
@cniweb I cannot exactly remember, but I think it was @cyberkov as he is also registered as an admin on Cloudbees.
Is there any reason why the build has to happen on Travis and cannot be done on Cloudbees? In general, I would very much prefer to have all builds happening on the same service and not end up with a too distributed and fragmented infrastructure.

**Comment by cyberkov** [comment]
Hi! 

Yes it was me who created the job. Travis CI provided an easy way to fire up a multiarch docker instance to build the images. I needed the Cloudbees job to notify travis of a new build.

Cheers Hannes

**Comment by cniweb** [comment]
Can you Register my as an admin on Cloudbees, too?
Then I can configure it.

**Comment by kaikreuzer** [comment]
Can you sign up yourself with your github id here? https://www.cloudbees.com/signup
I can then add you to our instance.
Btw, Cloudbees also offers Docker plugins, so I would assume that it is possible to build everything there as well, so that we do not have to divert to Travis.

**Comment by reslip1** [comment]
It doesn't look like Travis is updating the 2.1.0-snapshot or 2.0.0 docker builds. These are out of date on the docker repository.

**Comment by RyanRamchandar** [comment]
Yes, the last push to https://hub.docker.com/r/openhab/openhab/tags/ was 21 days ago.

Is the push mechanism broken?

**Comment by cyberkov** [comment]
Indeed it is. The Jenkins job uses to run 'make trigger' which got removed in 8d9b357 by @legacycode
We would need to reconfigure the job to use curl directly.

**Comment by cyberkov** [comment]
I fixed the trigger in cloudbees, so it'll notify travis-ci upon a new build is done.

Unfortunately I cannot be of any help regarding the migration to cloudbees :(

Cheers Hannes

**Comment by legacycode** [comment]
Another option is to use travis cron job feature. It should be on the bottom of the the https://travis-ci.org/openhab/openhab-docker/settings page. Maybe it is better to buid the docker container once a day.

**Comment by cyberkov** [comment]
Yes and no. It's nice to put a "daily build" sticker on your software but I don't see the benefit when I can build whenever a "good build" of openhab is available and I can package it then. It makes pushing bugfix releases throughout the day easier. 
As a fallback if the hook is not working it would make sense but I'd prefer to just keep the hook.
