### ISSUE TITLE
timezone problem

### ISSUE THREAD

**Issue by Wurzelseppi** [openhab/openhab-docker#82]
Hi guys,

just installed the new image.
I have the problem, that my host has the right time 

Tue Feb 14 21:21:31 CET 2017
but inside the docker it shows                                       
Tue Feb 14 20:19:18 UTC 2017

I made the mounts like described:

-v /etc/localtime:/etc/localtime:ro -v /etc/timezone:/etc/timezone:ro 

What´s´wrong here ?

**Comment by legacycode** [comment]
Hi,

i can not reproduce the problem. The following run commands works for me.

```
docker run --rm -v /etc/localtime:/etc/localtime -v /etc/timezone:/etc/timezone openhab/openhab:2.0.0-amd64 cat /etc/timezone
```
returns: **Europe/Berlin**

```
docker run --rm -v /etc/localtime:/etc/localtime -v /etc/timezone:/etc/timezone openhab/openhab:2.0.0-amd64 date
```
returns: **Tue Feb 14 21:38:13 CET 2017**

How did you checked the date?

**Comment by Wurzelseppi** [comment]
Hi there,
on my Synology (DS916+) I have a kitematic like dockersupport, which lets me enter the bash of the docker over an web-ui.
Anyway, when I do that and compare the date of the bash output of the docker and the host machine I get the difference of 1 hour ....
Tonight, when i got back from work, I´ll check the mounts of localtime and timezone inside the container, but from outside everything seems to be fine ...
Sorry, but yesterday I was just shortly on my machine and couldn´t check much ....

**Comment by Wurzelseppi** [comment]
Hi there, hmmmm... it´s working all of a sudden ..... Problem was on my side then, sry

**Comment by ahielg** [comment]
@Wurzelseppi I'm having the same problem
docker run --net=host -v /etc/localtime:/etc/localtime:ro -v /etc/timezone:/etc/timezone:ro  openhab/openhab:2.2.0-amd64-debian

in the bash I see the correct time, but in the openhab logs and the rules the date is still GMT...

Any suggestions?
(I've updated the timezone in paperUI and still it didn't help...)
