### ISSUE TITLE
User properties made in paper ui not persistent

### ISSUE THREAD

**Issue by Wurzelseppi** [openhab/openhab-docker#84]
Hi guys,

just a question. When i set the UI Service Configuration (in my case icon format -> Bitmap) and restart the docker image the setting is gone (back to vector).
Anyone knows about this ?

I made a analog thread here for you guys to watch:
https://community.openhab.org/t/docker-ui-service-configuration-not-persistent/23122/1

**Comment by Wurzelseppi** [comment]
when i change the setting (org.eclipse.smarthome.basicui:iconType=png) in basicui.cfg it survives the restart.

**Comment by wborn** [comment]
I just had a look at this issue @Wurzelseppi but it seems to work as expected. Settings made in the configuration files will override those made in Paper UI after a restart.

So what most likely happened is that you choose the "Demo" package setup on the first run of the container. This creates the file `/conf/services/basicui.cfg` with:

```
# The icon type to use, either png or svg
org.eclipse.smarthome.basicui:iconType=svg
```

Upon restarting the container it will reset the iconType setting to "svg". 

So you can either:
* remove `/conf/services/basicui.cfg` so defaults (those made in Paper UI) are used
* remove/comment `org.eclipse.smarthome.basicui:iconType=svg` in `/conf/services/basicui.cfg` to stop overriding it
* choose another package setup on the first run (e.g. "Standard") so `basicui.cfg` is not created at all
