### ISSUE TITLE
Arm images

### ISSUE THREAD

**Issue by craigham** [openhab/openhab-docker#90]
Does anyone know why the armhf images are no longer created?  It has been 15 days and there have been multiple builds since.

**Comment by cniweb** [comment]
The problem is here:
https://travis-ci.org/openhab/openhab-docker/jobs/239208413#L1299
But I don´t no, wath can we do...

**Comment by legacycode** [comment]
This is an qemu issue. I linked the original problem above. I removed the gosu integration check and created PR #93. Hopefully they will fix this issue and we can add the integration check again.

**Comment by cniweb** [comment]
👍

**Comment by craigham** [comment]
Awesome.  Thanks
